### ISSUE TITLE
 jx step git credentials running on minikube build invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by pasikon** [jenkins-x/jx#1112]
```
+ jx step git credentials
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x13ca1cf]

goroutine 1 [running]:
github.com/jenkins-x/jx/pkg/kube.CurrentNamespace(...)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/kube/config.go:32
github.com/jenkins-x/jx/pkg/jx/cmd/util.(*factory).CreateClient(0xc420128ba0, 0xc420000180, 0x300000002, 0xc420000180, 0xc420655a80, 0x43311f, 0xc420000180)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/util/factory.go:362 +0xaf
github.com/jenkins-x/jx/pkg/jx/cmd.(*CommonOptions).KubeClient(0xc42062fef0, 0x46dfdf, 0x102, 0xffffffffffffff9c, 0xc420012e00, 0x1f0, 0x0)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/common.go:109 +0x8c
github.com/jenkins-x/jx/pkg/jx/cmd.(*CommonOptions).LoadPipelineSecrets(0xc42062fef0, 0x1d4ac64, 0x3, 0x0, 0x0, 0xb, 0xc4200b41e0, 0xc420655c70)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/common_auth.go:100 +0x43
github.com/jenkins-x/jx/pkg/jx/cmd.(*StepGitCredentialsOptions).Run(0xc42062fef0, 0xc420655c50, 0x0)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/step_git_credentials.go:94 +0xba
github.com/jenkins-x/jx/pkg/jx/cmd.NewCmdStepGitCredentials.func1(0xc420642a00, 0x2c2c508, 0x0, 0x0)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/step_git_credentials.go:67 +0x73
github.com/jenkins-x/jx/vendor/github.com/spf13/cobra.(*Command).execute(0xc420642a00, 0x2c2c508, 0x0, 0x0, 0xc420642a00, 0x2c2c508)
	/home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/jenkins-x/jx/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420168280, 0xc4204af900, 0xc420675900, 0xc420663900)
	/home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/spf13/cobra/command.go:852 +0x334
github.com/jenkins-x/jx/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420168280, 0xc420128ba0, 0x2ac7340)
	/home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/jenkins-x/jx/cmd/jx/app.Run(0xc4205fdf70, 0x18a3479)
	/home/jenkins/go/src/github.com/jenkins-x/jx/cmd/jx/app/jx.go:18 +0x90
main.main()
	/home/jenkins/go/src/github.com/jenkins-x/jx/cmd/jx/jx.go:10 +0x22
```

**Comment by rafaelfbs** [comment]
First, i'm new to this project but i loved it! Maybe i can help a little 😄

We have two possibilities:

- JX did not load your kubeconfig, returning nil;
- Kubeconfig file is malformed and does not have a _current-context_ or _contexts_ properties;

So, we could add a nil check on _LoadConfig_ to return an error:
```go
config, err := po.GetStartingConfig() 
if err != nil { 
    return nil, po, fmt.Errorf("Could not load the kube config file %s due to %s", po.GetDefaultFilename(), err) 
}
if config == nil {
    return nil, po, fmt.Errorf("Failed to load Kubernetes Config!")
}
```

However, it will throw the same error if we have a malformed kubeconfig. So, add another check in _CurrentNamespace_
```go
ctx := CurrentContext(config)
if ctx != nil {
  return ""
}
return ctx.Namespace
```
Btw, i prefer the (string, error) style than just passing an empty string.

### Stacktrace codes

https://github.com/jenkins-x/jx/blob/a1c5194023146fd7c8f8f7a3a62273ac5ff3b852/pkg/jx/cmd/util/factory.go#L345-L365

https://github.com/jenkins-x/jx/blob/a1c5194023146fd7c8f8f7a3a62273ac5ff3b852/pkg/kube/config.go#L17-L27

https://github.com/jenkins-x/jx/blob/a1c5194023146fd7c8f8f7a3a62273ac5ff3b852/pkg/kube/config.go#L30-L33

https://github.com/jenkins-x/jx/blob/a1c5194023146fd7c8f8f7a3a62273ac5ff3b852/pkg/kube/config.go#L36-L44

**Comment by pasikon** [comment]
thats after I upgraded jx to 1.3.20, before that it apparently was loading config correctly. now with jx 1.3.20:

`jx version`:

`error: an empty namespace may not be set during creation`

**Comment by rafaelfbs** [comment]
PR #1110

**Comment by pasikon** [comment]
@rafaelfbs I think why jx 1.3.20 is not loading the config should also be invesitigated :)

**Comment by jstrachan** [comment]
@rafaelfbs many thanks for all your help on this issue! It was a regression in a recent fix - I've reverted the commit now and we're just rolling out new releases of everything; should bbe done within the hour...

**Comment by pasikon** [comment]
its working thanks!

**Comment by rafaelfbs** [comment]
Nice! What was the issue PR #1110 intended to resolve?

@i0n Could you describe the problem?
