### ISSUE TITLE
jx step git credentials running on GKE panic runtime error invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by davecore82** [jenkins-x/jx#1126]
I'm doing "jx create quickstart" and choosing the golang quickstart and the build fails with this output:

```
[gokubecon] Running shell script
+ jx step git credentials

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x13ca24f]

goroutine 1 [running]:
github.com/jenkins-x/jx/pkg/kube.CurrentNamespace(...)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/kube/config.go:32
github.com/jenkins-x/jx/pkg/jx/cmd/util.(*factory).CreateClient(0xc4201042e0, 0xc420000180, 0x300000002, 0xc420000180, 0xc4205f3a80, 0x43311f, 0xc420000180)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/util/factory.go:362 +0xaf
github.com/jenkins-x/jx/pkg/jx/cmd.(*CommonOptions).KubeClient(0xc4206afef0, 0x46dfdf, 0x102, 0xffffffffffffff9c, 0xc4206b2f80, 0x1f0, 0x0)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/common.go:109 +0x8c
github.com/jenkins-x/jx/pkg/jx/cmd.(*CommonOptions).LoadPipelineSecrets(0xc4206afef0, 0x1d4ac64, 0x3, 0x0, 0x0, 0xb, 0xc4206d6000, 0xc4205f3c70)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/common_auth.go:100 +0x43
github.com/jenkins-x/jx/pkg/jx/cmd.(*StepGitCredentialsOptions).Run(0xc4206afef0, 0xc4205f3c50, 0x0)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/step_git_credentials.go:94 +0xba
github.com/jenkins-x/jx/pkg/jx/cmd.NewCmdStepGitCredentials.func1(0xc4206d1b80, 0x2c2c508, 0x0, 0x0)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/step_git_credentials.go:67 +0x73
github.com/jenkins-x/jx/vendor/github.com/spf13/cobra.(*Command).execute(0xc4206d1b80, 0x2c2c508, 0x0, 0x0, 0xc4206d1b80, 0x2c2c508)
	/home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/jenkins-x/jx/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4200a6780, 0xc4206c0c80, 0xc4206a8c80, 0xc4206a4c80)
	/home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/spf13/cobra/command.go:852 +0x334
github.com/jenkins-x/jx/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4200a6780, 0xc4201042e0, 0x2ac7340)
	/home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/jenkins-x/jx/cmd/jx/app.Run(0xc420597f70, 0x18a35a9)
	/home/jenkins/go/src/github.com/jenkins-x/jx/cmd/jx/app/jx.go:18 +0x90
main.main()
	/home/jenkins/go/src/github.com/jenkins-x/jx/cmd/jx/jx.go:10 +0x22

script returned exit code 2
```

I'm running from the Google cloud shell:

```
$ jx version
NAME               VERSION
jx                 1.3.27
jenkins x platform 0.0.1515
kubernetes cluster v1.8.10-gke.0
kubectl            v1.9.7
helm client        v2.9.1+g20adb27
helm server        v2.9.1+g20adb27
git                git version 2.11.0
```

This looks similar to this other issue https://github.com/jenkins-x/jx/issues/1112 

Thanks,
David

**Comment by davecore82** [comment]
Not sure this helps but I just noticed I have pods in CrashLoopBackOff:

```
jx-staging    jx-staging-python-http-6799d6cdc9-2t78w                0/1       CrashLoopBackOff   28         2h
jx-staging    jx-staging-pythonquickstart-cf586bcc9-xmhmp            0/1       CrashLoopBackOff   25         1h
jx            skaffold-74d6cc64f7-6vbrh                              0/1       CrashLoopBackOff   26         1h
```

The two python ones I'm guessing are from previous unrelated attempts (which gave me 503 web browser errors but that's another story) but I wonder if the skaffold one is related to this issue.

**Comment by davecore82** [comment]
Tried it again from a new cluster and same issue. Running "jx step git credentials -o filename" manually works though.

**Comment by davecore82** [comment]
jx status is good:

`Jenkins X checks passed for Cluster(gke_ineproject-203603_us-east4-a_eyewell): 3 nodes, memory 8% of 38120088Ki, cpu 23% of 11760m. Jenkins is running at http://jenkins.jx.35.236.255.61.nip.io
`

jx logs jenkins showed me this:

```
Jun 23, 2018 4:58:37 AM org.csanchez.jenkins.plugins.kubernetes.pipeline.ContainerExecDecorator$1 doLaunch
INFO: Created process inside pod: [go-wf31h], container: [go] with pid:[-1]
Jun 23, 2018 4:58:39 AM okhttp3.internal.platform.Platform log
INFO: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
Jun 23, 2018 4:58:40 AM org.csanchez.jenkins.plugins.kubernetes.pipeline.ContainerExecDecorator$1 doLaunch
INFO: Created process inside pod: [go-wf31h], container: [go] with pid:[-1]
Jun 23, 2018 4:58:41 AM okhttp3.internal.platform.Platform log
INFO: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
Jun 23, 2018 4:58:44 AM org.csanchez.jenkins.plugins.kubernetes.pipeline.ContainerExecDecorator$1 doLaunch
INFO: Created process inside pod: [go-wf31h], container: [go] with pid:[-1]

Jun 23, 2018 4:58:44 AM okhttp3.internal.platform.Platform log
INFO: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?

Jun 23, 2018 4:58:47 AM org.csanchez.jenkins.plugins.kubernetes.pipeline.ContainerExecDecorator$1 doLaunch
INFO: Created process inside pod: [go-wf31h], container: [go] with pid:[-1]


Jun 23, 2018 4:58:48 AM org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave _terminate
INFO: Terminating Kubernetes instance for agent go-wf31h
Jun 23, 2018 4:58:48 AM jenkins.slaves.DefaultJnlpSlaveReceiver channelClosed
WARNING: Computer.threadPoolForRemoting [#51] for go-wf31h terminated
java.nio.channels.ClosedChannelException
	at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer.onReadClosed(ChannelApplicationLayer.java:209)
	at org.jenkinsci.remoting.protocol.ApplicationLayer.onRecvClosed(ApplicationLayer.java:222)
	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecvClosed(ProtocolStack.java:832)
	at org.jenkinsci.remoting.protocol.FilterLayer.onRecvClosed(FilterLayer.java:287)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.onRecvClosed(SSLEngineFilterLayer.java:181)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.switchToNoSecure(SSLEngineFilterLayer.java:283)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processWrite(SSLEngineFilterLayer.java:503)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processQueuedWrites(SSLEngineFilterLayer.java:248)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.doSend(SSLEngineFilterLayer.java:200)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.doCloseSend(SSLEngineFilterLayer.java:213)
	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.doCloseSend(ProtocolStack.java:800)
	at org.jenkinsci.remoting.protocol.ApplicationLayer.doCloseWrite(ApplicationLayer.java:173)
	at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer$ByteBufferCommandTransport.closeWrite(ChannelApplicationLayer.java:314)
	at hudson.remoting.Channel.close(Channel.java:1450)
	at hudson.remoting.Channel.close(Channel.java:1403)
	at hudson.slaves.SlaveComputer.closeChannel(SlaveComputer.java:769)
	at hudson.slaves.SlaveComputer.access$800(SlaveComputer.java:102)
	at hudson.slaves.SlaveComputer$3.run(SlaveComputer.java:687)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)


Jun 23, 2018 4:58:48 AM org.jenkinsci.plugins.workflow.job.WorkflowRun finish
INFO: davecore82/gonewtest/master #1 completed: FAILURE
Jun 23, 2018 4:58:48 AM okhttp3.internal.platform.Platform log
INFO: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
Jun 23, 2018 4:58:48 AM org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave _terminate
INFO: Terminated Kubernetes instance for agent jx/go-wf31h
EXITCODE   0EXITCODE   0EXITCODE   0Terminated Kubernetes instance for agent jx/go-wf31h
Jun 23, 2018 4:58:48 AM org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave _terminate
INFO: Disconnected computer go-wf31h
Jun 23, 2018 4:58:49 AM org.jenkinsci.plugins.jx.resources.BuildSyncRunListener upsertBuild
INFO: Updated  pipeline activity davecore82-gonewtest-master-1
```

"kubectl get pods --all-namespaces" looks good

**Comment by jstrachan** [comment]
This was an issue yesterday but has been fixed AFAIK.

Could you try

```
jx upgrade platform
jx version
jx start pipeline
```
and see if the core dump is gone?

**Comment by davecore82** [comment]
I tried again this morning. I had deleted my environment since yesterday so I started from scratch and I ended up with this:

```
$ jx version
NAME               VERSION
jx                 1.3.27
jenkins x platform 0.0.1531
kubernetes cluster v1.8.10-gke.0
kubectl            v1.10.3
helm client        v2.9.1+g20adb27
helm server        v2.9.1+g20adb27
git                git version 2.14.1
```

And now it works:

`    Promoted                                 2m46s    2m42s Succeeded Application is at: http://gosaturdaymorning.jx-staging.35.237.80.226.nip.io`


I guess somehow I was using an older jenkins x platform yesterday. Thanks!
