### ISSUE TITLE
Old jx image version 1.3.21 in cronjobs

### ISSUE THREAD

**Issue by michaelfig** [jenkins-x/jx#1131]
Hi,

First, thanks for Jenkins X... it looks to be shaping up into the platform I'm wanting for our organization.

I'm getting thousands of errored cron jobs in both jenkins-x-gc-previews and jenkins-x-gc-activities pods.  They all look the same:

```
sh-3.2# jx version
NAME               VERSION
jx                 1.3.27
jenkins x platform 0.0.1531
kubernetes cluster v1.10.4
kubectl            v1.10.1
helm client        v2.9.1+g20adb27
helm server        v2.9.1+g20adb27
git                git version 2.15.2 (Apple Git-101.1)
sh-3.2# kubectl logs jenkins-x-gc-previews-1529852400-zzvcp
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x13c9ee9]

goroutine 1 [running]:
github.com/jenkins-x/jx/pkg/kube.CurrentNamespace(...)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/kube/config.go:32
github.com/jenkins-x/jx/pkg/jx/cmd/util.(*factory).CreateJXClient(0xc42011aac0, 0xc420381180, 0x452c20, 0xc420381180, 0xc4207d01e0, 0xc42030ed58, 0xc42075b538)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/util/factory.go:320 +0x89
github.com/jenkins-x/jx/pkg/jx/cmd.(*GCPreviewsOptions).Run(0xc420740c40, 0xc42075bc50, 0x0)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/gc_previews.go:72 +0x6d
github.com/jenkins-x/jx/pkg/jx/cmd.NewCmdGCPreviews.func1(0xc4204a7180, 0x2c2c508, 0x0, 0x0)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/gc_previews.go:61 +0x75
github.com/jenkins-x/jx/vendor/github.com/spf13/cobra.(*Command).execute(0xc4204a7180, 0x2c2c508, 0x0, 0x0, 0xc4204a7180, 0x2c2c508)
	/home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/jenkins-x/jx/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc42015c280, 0xc4201c7900, 0xc4203d9900, 0xc42064f900)
	/home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/spf13/cobra/command.go:852 +0x334
github.com/jenkins-x/jx/vendor/github.com/spf13/cobra.(*Command).Execute(0xc42015c280, 0xc42011aac0, 0x2ac7340)
	/home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/jenkins-x/jx/cmd/jx/app.Run(0xc4205bbf70, 0x18a35a9)
	/home/jenkins/go/src/github.com/jenkins-x/jx/cmd/jx/app/jx.go:18 +0x90
main.main()
	/home/jenkins/go/src/github.com/jenkins-x/jx/cmd/jx/jx.go:10 +0x22
sh-3.2# kubectl logs jenkins-x-gc-activities-1529852400-zt7rl
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x13c9ee9]

goroutine 1 [running]:
github.com/jenkins-x/jx/pkg/kube.CurrentNamespace(...)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/kube/config.go:32
github.com/jenkins-x/jx/pkg/jx/cmd/util.(*factory).CreateJXClient(0xc42014e860, 0xc4206f3e00, 0x2ad6780, 0xc42016d348, 0x1d51569, 0x8, 0x0)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/util/factory.go:320 +0x89
github.com/jenkins-x/jx/pkg/jx/cmd.(*GCActivitiesOptions).Run(0xc4202a0680, 0xc420245c50, 0x0)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/gc_activities.go:73 +0x61
github.com/jenkins-x/jx/pkg/jx/cmd.NewCmdGCActivities.func1(0xc420778280, 0x2c2c508, 0x0, 0x0)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/gc_activities.go:62 +0x75
github.com/jenkins-x/jx/vendor/github.com/spf13/cobra.(*Command).execute(0xc420778280, 0x2c2c508, 0x0, 0x0, 0xc420778280, 0x2c2c508)
	/home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/jenkins-x/jx/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420170280, 0xc420248000, 0xc420796c80, 0xc42064db80)
	/home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/spf13/cobra/command.go:852 +0x334
github.com/jenkins-x/jx/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420170280, 0xc42014e860, 0x2ac7340)
	/home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/jenkins-x/jx/cmd/jx/app.Run(0xc4207c3f70, 0x18a35a9)
	/home/jenkins/go/src/github.com/jenkins-x/jx/cmd/jx/app/jx.go:18 +0x90
main.main()
	/home/jenkins/go/src/github.com/jenkins-x/jx/cmd/jx/jx.go:10 +0x22
sh-3.2# 
```

**Comment by michaelfig** [comment]
I found that the cronjobs were still using  jenkinsxio/jx:1.3.21 even though I installed from scratch using jx 1.3.27.  The following patch seemed to make things go further for me:

```
sh-3.2# kubectl patch cronjob jenkins-x-gc-previews -p '{"spec":{"jobTemplate":{"spec":{"template":{"spec":{"containers":[{"name":"gc-previews","image":"jenkinsxio/jx:1.3.27"}]}}}}}}'
cronjob.batch "jenkins-x-gc-previews" patched
sh-3.2# kubectl patch cronjob jenkins-x-gc-activities -p '{"spec":{"jobTemplate":{"spec":{"template":{"spec":{"containers":[{"name":"gc-activities","image":"jenkinsxio/jx:1.3.27"}]}}}}}}'
cronjob.batch "jenkins-x-gc-activities" patched
sh-3.2#
```

Now I get a failure in the activities job:
```
error: pipelineactivities.jenkins.io is forbidden: User "system:serviceaccount:jx:jenkins-x-gc-activities" cannot list pipelineactivities.jenkins.io in the namespace "jx"
```

and in the previews job:
```
error: environments.jenkins.io is forbidden: User "system:serviceaccount:jx:jenkins-x-gc-previews" cannot list environments.jenkins.io in the namespace "jx"
```

**Comment by michaelfig** [comment]
Even after the jx version is updated, it looks now like #1071

**Comment by rawlingsj** [comment]
I've just tested with the latest Jenkins X platform release and the cronjobs complete successfully.

I wonder could you try to upgrade to this specific version please?
```
jx upgrade platform --version 0.0.1533
```

**Comment by rawlingsj** [comment]
Oh and you'll need the latest `jx` binary to use the specific `--version` flag above.

**Comment by pasikon** [comment]
@michaelfig what worked for me was deleting both cronjobs and upgrading platform with jx

**Comment by rawlingsj** [comment]
the gc cron jobs should be fixed now in the latest release which is now available.

```
jx upgrade cli
jx upgrade platform
jx version
```

you should get `0.0.1547` for the platform version which has this fix
