### ISSUE TITLE
Getting "Found remote branch names (...) panic: runtime error: slice bounds out of range" when promoting an app

### ISSUE THREAD

**Issue by darthcabs** [jenkins-x/jx#1372]
### Summary 
Background: I created a python-http repo using `jx create quickstart`, played around with it, then removed the app. Later on I `jx import --url` the same repo, it built successfully. Now when I issue `jx promote -a darthcabs/python-web/master --env env1`, I receive this following error:

_Found remote branch names delete-environment-jx-prod, delete-environment-jx-staging, delete-python-web, delete-python-web-214f9336-90ec-11e8-9f92-107d1a0a09b8, delete-python-web-64a233ab-906a-11e8-a599-107d1a0a09b8, delete-python-web-f11e047a-9062-11e8-86c3-107d1a0a09b8, master, HEAD -> origin/master, delete-python-web, delete-python-web-f11e047a-9062-11e8-86c3-107d1a0a09b8, master
panic: runtime error: slice bounds out of range_

I suspect that if I hadn't played so much around with this repo, I wouldn't receive this error. Still it's something that could easily affect a production scenario, where apps get removed and added all the time. OR I may be completely wrong and what caused this issue is something else haha.

### Jx version

The output of `jx version` is:
```
jx                             1.3.117
jenkins x platform    0.0.1881
kubernetes cluster   v1.9.8
kubectl                     v1.11.0
helm client               v2.10.0-rc.1+gaa98e7e
helm server             v2.10.0-rc.1+gaa98e7e
git                            git version 2.13.3
```

### Kubernetes cluster

Installed jenkins-x on a pre-existing k8s cluster on AWS, deployed with Kops. `jx compliance` tests all passed.

### Operating system / Environment

linux-amd64

### Expected behavior
The app after creating ECR and building the image, would be promoted succesfully to the environment upon issuing `jx promote`.

### Actual behavior

I received a _Found remote branch names (...) panic: runtime error: slice bounds out of range_ error.

**Comment by jstrachan** [comment]
any chance there was a line number in the panic? :)

**Comment by smaslennikov** [comment]
I've got the same issue:

```bash
$ jx promote testobjects -e production
Promoting latest version of app testobjects to namespace jx-production
pipeline me/testobjects/master
Using pipeline: me/testobjects/master build: #1
Found remote branch names master, promote-testobjects-latest, promote-testobjects-latest-65d77b2b-b6ca-11e8-9b29-c20025910301, promote-testobjects-latest-760917a1-b6ca-11e8-b9da-c20025910301, promote-testobjects-latest-95e4216e-b6ca-11e8-9c8b-c20025910301, promote-testobjects-latest-99603fdd-b6ca-11e8-b0dc-c20025910301, promote-testobjects-latest-c835e321-b6ca-11e8-adb0-c20025910301, HEAD -> origin/master, master
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/jenkins-x/jx/pkg/helm.(*HelmCLI).SearchChartVersions(0xc4208bfc50, 0x7ffeefbff9bb, 0xb, 0x132d5cf, 0xc420b33328, 0x0, 0x0, 0x1027db9)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/helm/helm_cli.go:251 +0x45f
github.com/jenkins-x/jx/pkg/jx/cmd.(*PromoteOptions).findLatestVersion(0xc420964000, 0x7ffeefbff9bb, 0xb, 0x1e900bf, 0xc420a06300, 0xf5, 0x2f5)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/promote.go:659 +0x76
github.com/jenkins-x/jx/pkg/jx/cmd.(*PromoteOptions).PromoteViaPullRequest.func1(0xc4208e29e0, 0x5e, 0xc4208e29e0)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/promote.go:394 +0xb4
github.com/jenkins-x/jx/pkg/jx/cmd.(*CommonOptions).createEnvironmentPullRequest(0xc420964000, 0xc420844000, 0xc420010900, 0xc4206de1e0, 0x1a, 0xc4206de200, 0x15, 0xc420979650, 0x25, 0x0, ...)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/common_environments.go:116 +0x7d4
github.com/jenkins-x/jx/pkg/jx/cmd.(*PromoteOptions).PromoteViaPullRequest(0xc420964000, 0xc420844000, 0xc42004cf80, 0x2dfe236, 0x1)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/promote.go:402 +0x385
github.com/jenkins-x/jx/pkg/jx/cmd.(*PromoteOptions).Promote(0xc420964000, 0xc420972270, 0xd, 0xc420844000, 0x1, 0x7ffeefbff9bb, 0xb, 0xc42081e2e0)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/promote.go:322 +0x917
github.com/jenkins-x/jx/pkg/jx/cmd.(*PromoteOptions).Run(0xc420964000, 0x0, 0x0)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/promote.go:221 +0x422
github.com/jenkins-x/jx/pkg/jx/cmd.NewCmdPromote.func1(0xc420b20a00, 0xc42002baa0, 0x1, 0x3)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/promote.go:116 +0x70
github.com/jenkins-x/jx/vendor/github.com/spf13/cobra.(*Command).execute(0xc420b20a00, 0xc42002ba70, 0x3, 0x3, 0xc420b20a00, 0xc42002ba70)
	/home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/jenkins-x/jx/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc42042cc80, 0xc420b0ea00, 0xc420b4d180, 0xc420b18f00)
	/home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/spf13/cobra/command.go:852 +0x30a
github.com/jenkins-x/jx/vendor/github.com/spf13/cobra.(*Command).Execute(0xc42042cc80, 0xc420aac0c0, 0x30363a0)
	/home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/jenkins-x/jx/cmd/jx/app.Run(0xc42084ff78, 0xc4200b6058)
	/home/jenkins/go/src/github.com/jenkins-x/jx/cmd/jx/app/jx.go:17 +0x90
main.main()
	/home/jenkins/go/src/github.com/jenkins-x/jx/cmd/jx/jx.go:10 +0x22
```

This is on a cluster I just created today. Since then, I imported this testobjects repo, got it running with a few commits, but can't promote to production. @jstrachan do you need anything else to help diagnose this issue?
