### ISSUE TITLE
jx create docker auth fails

### ISSUE THREAD

**Issue by davidvanlaatum** [jenkins-x/jx#1635]
### Summary 
jx create docker auth fails

### Steps to reproduce the behavior
```
jx create docker auth --host=dockerregistry.x.com --user=x --email=x@y.com --secret=XXXXXX
? Please provide email ID for the host: dockerregistry.x.com  and user: x x@y.com
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/jenkins-x/jx/pkg/jx/cmd.(*CreateDockerAuthOptions).Run(0xc000028540, 0x0, 0x0)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/create_docker_auth.go:130 +0x71d
github.com/jenkins-x/jx/pkg/jx/cmd.NewCmdCreateDockerAuth.func1(0xc0006a3680, 0xc000161e50, 0x1, 0x5)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/create_docker_auth.go:69 +0x66
github.com/jenkins-x/jx/vendor/github.com/spf13/cobra.(*Command).execute(0xc0006a3680, 0xc000161e00, 0x5, 0x5, 0xc0006a3680, 0xc000161e00)
	/home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/spf13/cobra/command.go:766 +0x2cc
github.com/jenkins-x/jx/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0000f6a00, 0xc0008b6000, 0xc0008d3680, 0xc0008c6780)
	/home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/jenkins-x/jx/vendor/github.com/spf13/cobra.(*Command).Execute(0xc0000f6a00, 0xc0007a11c0, 0x33e72e0)
	/home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/jenkins-x/jx/cmd/jx/app.Run(0xc000861f88, 0xc0000a0058)
	/home/jenkins/go/src/github.com/jenkins-x/jx/cmd/jx/app/jx.go:17 +0x90
main.main()
	/home/jenkins/go/src/github.com/jenkins-x/jx/cmd/jx/jx.go:10 +0x22
```

### Jx version

The output of `jx version` is:
NAME               VERSION
jx                 1.3.245
jenkins x platform 0.0.2328
kubernetes cluster v1.11.2
kubectl            v1.11.3
helm client        v2.10.0+g9ad53aa
helm server        v2.10.0+g9ad53aa
git                git version 2.15.2 (Apple Git-101.1)

### Kubernetes cluster

standalone on vcenter

### Operating system / Environment

client is osx 10.13.6
kube cluster is centos 7

### Actual behavior
reprompts for email then crashes

**Comment by davidvanlaatum** [comment]
The secret in kube just had {} in it once I copied in a working json file the command works

**Comment by angoothachap** [comment]
https://github.com/jenkins-x/jx/pull/1658
