### ISSUE TITLE
Fales negative error on jx create issue on bitbucket

### ISSUE THREAD

**Issue by daya** [jenkins-x/jx#1668]
### Summary 
On bitbucket an issue gets created but an exception is thrown by `jx create issue`

### Steps to reproduce the behavior
try it on bitbucket

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.260
jenkins x platform 0.0.2328
kubernetes cluster v1.10.3
kubectl            v1.11.3
helm client        v2.10.0+g9ad53aa
helm server        v2.10.0+g9ad53aa
git                git version 2.17.1

```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

### Expected behavior
should create issue without throwing exception

### Actual behavior
```
rails-shopping-cart|master⚡ ⇒ jx create issue -t "making app RAILS_ENV environment aware"
? Do you wish to use dayasharma as the user name to use for authenticating with git issues Yes
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe4bbad]

goroutine 1 [running]:
github.com/jenkins-x/jx/pkg/gits.BitbucketIssueToGitIssue(0xc0006b6283, 0x5, 0xc00084e210, 0x4, 0xc0001de0f0, 0xc0008fe1e0, 0x26, 0xc000180360, 0x0, 0x1e25ba48, ...)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/gits/bitbucket_cloud.go:687 +0x26d
github.com/jenkins-x/jx/pkg/gits.(*BitbucketCloudProvider).CreateIssue(0xc00043f520, 0xc0002533e6, 0xc, 0xc0002533f3, 0x1f, 0xc0001e4c40, 0x242db20, 0x41a5401, 0xc0001e4c40)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/gits/bitbucket_cloud.go:780 +0x30e
github.com/jenkins-x/jx/pkg/issues.(*GitIssueProvider).CreateIssue(0xc0006d56b0, 0xc0001e4c40, 0x0, 0x0, 0xc0006d56b0)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/issues/git_provider.go:65 +0x61
github.com/jenkins-x/jx/pkg/jx/cmd.(*CreateIssueOptions).Run(0xc000264700, 0x0, 0x0)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/create_issue.go:99 +0xdb
github.com/jenkins-x/jx/pkg/jx/cmd.NewCmdCreateIssue.func1(0xc0008c0f00, 0xc000618ea0, 0x0, 0x2)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/create_issue.go:72 +0x66
github.com/jenkins-x/jx/vendor/github.com/spf13/cobra.(*Command).execute(0xc0008c0f00, 0xc000618e80, 0x2, 0x2, 0xc0008c0f00, 0xc000618e80)
	/home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/spf13/cobra/command.go:766 +0x2cc
github.com/jenkins-x/jx/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0000fca00, 0xc000612000, 0xc00062b900, 0xc00061e780)
	/home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/jenkins-x/jx/vendor/github.com/spf13/cobra.(*Command).Execute(0xc0000fca00, 0xc000573820, 0x286bbc0)
	/home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/jenkins-x/jx/cmd/jx/app.Run(0xc000933f88, 0xc0000460b8)
	/home/jenkins/go/src/github.com/jenkins-x/jx/cmd/jx/app/jx.go:17 +0x90
main.main()
	/home/jenkins/go/src/github.com/jenkins-x/jx/cmd/jx/jx.go:10 +0x22
```
listing the issues `jx get issues` shows the issue has been created

**Comment by wbrefvem** [comment]
@daya I was able to reproduce your issue and should have a fix soon.
