### ISSUE TITLE
fix broken unit test after moving to serverless jenkins

### ISSUE THREAD

**Issue by rawlingsj** [jenkins-x/jx#1868]
after moving to serverless jenkins we had 6 failing unit tests in `import_test.go`, the failures relate to using paths which seem to have a problem in one shot jenkins.  Possibly due to symlinks in the jenkinsfile running? 

example test failure:

```
--- FAIL: TestCreateProwOwnersFileCreateWhenDoesNotExist (0.00s)
    import_test.go:65:
        	Error Trace:	import_test.go:65
        	Error:      	Received unexpected error:
        	            	open /home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/test_data/prow/no_owners_file/OWNERS: no such file or directory
        	Test:       	TestCreateProwOwnersFileCreateWhenDoesNotExist
        	Messages:   	There should be no error
panic: remove /home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/test_data/prow/no_owners_file/OWNERS: no such file or directory [recovered]
	panic: remove /home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/test_data/prow/no_owners_file/OWNERS: no such file or directory

goroutine 720 [running]:
testing.tRunner.func1(0xc0004fc600)
	/usr/local/go/src/testing/testing.go:792 +0x387
panic(0x1e76300, 0xc00098ee10)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/jenkins-x/jx/pkg/jx/cmd_test.cleanup(0xc000cdaae0, 0x5c)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/import_test.go:25 +0x62
github.com/jenkins-x/jx/pkg/jx/cmd_test.TestCreateProwOwnersFileCreateWhenDoesNotExist(0xc0004fc600)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/import_test.go:66 +0x23c
testing.tRunner(0xc0004fc600, 0x2271760)
	/usr/local/go/src/testing/testing.go:827 +0xbf
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:878 +0x353
```

We've had to disable these 6 tests so we can move forward with prow and serverless jenkins, this issue needs to be resolved so tracking here

**Comment by ccojocar** [comment]
Unit test seems to be fixed by now. Closing this issue.
