### ISSUE TITLE
Panic on upgrade platform following 1.3.451

### ISSUE THREAD

**Issue by mbeacom** [jenkins-x/jx#2038]
### Summary 

Following upgrading from `1.3.450` to `1.3.451` of the jx cli, I'm receiving:  

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x2a34802]

goroutine 1 [running]:
github.com/jenkins-x/jx/pkg/jx/cmd.(*UpgradePlatformOptions).Run(0xc0008ad000, 0x0, 0x0)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/upgrade_platform.go:160 +0x492
github.com/jenkins-x/jx/pkg/jx/cmd.NewCmdUpgradePlatform.func1(0xc000818000, 0x4e5a950, 0x0, 0x0)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/upgrade_platform.go:69 +0x66
github.com/spf13/cobra.(*Command).execute(0xc000818000, 0x4e5a950, 0x0, 0x0, 0xc000818000, 0x4e5a950)
	/home/jenkins/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2cc
github.com/spf13/cobra.(*Command).ExecuteC(0xc0004c2280, 0xc0008d3400, 0xc000882000, 0xc000870780)
	/home/jenkins/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2fd
github.com/spf13/cobra.(*Command).Execute(0xc0004c2280, 0xc000850780, 0x35e89e0)
	/home/jenkins/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800 +0x2b
github.com/jenkins-x/jx/cmd/jx/app.Run(0xc000915f88, 0xc0000ac058)
	/home/jenkins/go/src/github.com/jenkins-x/jx/cmd/jx/app/jx.go:17 +0x97
main.main()
	/home/jenkins/go/src/github.com/jenkins-x/jx/cmd/jx/jx.go:10 +0x22
```

while attempting to `jx upgrade platform`

### Steps to reproduce the behavior

Upgrade to `jx` version `1.3.451` -> `jx upgrade platform`

### Jx version

The output of `jx version` is:

```
1.3.451
```

### Kubernetes cluster

AWS EKS - TF community EKS module - v1.10

### Operating system / Environment

macos 10.14 (18A391)

### Expected behavior

Upgrade succeeds

### Actual behavior

`panic: runtime error: invalid memory address or nil pointer dereference`

**Comment by jtnord** [comment]
@mbeacom is this still an issue for you?

**Comment by ccojocar** [comment]
This issue seems to be fixed.
