### ISSUE TITLE
Pipelines permanently in Failure / Could not resolve host

### ISSUE THREAD

**Issue by fharris** [jenkins-x/jx#2101]
### Summary 
Pipelines permanently in Failure / Could not resolve host: github.com / ERROR: Could not do lightweight checkout, falling back to heavyweight
java.net.UnknownHostException: raw.githubusercontent.com: Temporary failure in name resolution

### Steps to reproduce the behavior
jx create spring -d web -d actuator

### Jx version

The output of `jx version` is:

```
1.3.453
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?
OKE , created with jx create cluster oke
### Operating system / Environment
Oracle Linux 7.4
### Expected behavior
Pipelines running
### Actual behavior
Pipelines in permanent failure

Branch indexing

Connecting to https://api.github.com with no credentials, anonymous access

GitHub API Usage: Current quota has 53 remaining (0 under budget). Next quota of 60 in 59 min

ERROR: Could not do lightweight checkout, falling back to heavyweight

java.net.UnknownHostException: raw.githubusercontent.com: Temporary failure in name resolution

	at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)

	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)

	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)

	at java.net.InetAddress.getAllByName0(InetAddress.java:1276)

	at java.net.InetAddress.getAllByName(InetAddress.java:1192)

	at java.net.InetAddress.getAllByName(InetAddress.java:1126)

	at com.squareup.okhttp.Dns$1.lookup(Dns.java:39)

	at com.squareup.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:175)

	at com.squareup.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:141)

	at com.squareup.okhttp.internal.http.RouteSelector.next(RouteSelector.java:83)

	at com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:174)

	at com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)

	at com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)

	at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)

	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)

	at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:450)

	at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:399)

	at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:236)

	at com.squareup.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)

	at com.squareup.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:25)

	at org.kohsuke.github.Requester.asStream(Requester.java:332)

	at org.kohsuke.github.GHContent.read(GHContent.java:117)

	at org.jenkinsci.plugins.github_branch_source.GitHubSCMFile.content(GitHubSCMFile.java:183)

	at jenkins.scm.api.SCMFile.contentAsString(SCMFile.java:338)

	at org.jenkinsci.plugins.workflow.multibranch.SCMBinder.create(SCMBinder.java:104)

	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:303)

	at hudson.model.ResourceController.execute(ResourceController.java:97)

	at hudson.model.Executor.run(Executor.java:429)

Checking out git https://github.com/fharris/environment-wingmisty-staging.git into /var/jenkins_home/workspace/nt-wingmisty-staging_master-EHWBI5BF5GUIFLH2WOCAVNHNP4QOVZA6XVO5COFQI7HAECH6MQTA@script to read Jenkinsfile

Cloning the remote Git repository

Cloning with configured refspecs honoured and without tags

Cloning repository https://github.com/fharris/environment-wingmisty-staging.git

 > git init /var/jenkins_home/workspace/nt-wingmisty-staging_master-EHWBI5BF5GUIFLH2WOCAVNHNP4QOVZA6XVO5COFQI7HAECH6MQTA@script # timeout=10

Fetching upstream changes from https://github.com/fharris/environment-wingmisty-staging.git

 > git --version # timeout=10

 > git fetch --no-tags --progress https://github.com/fharris/environment-wingmisty-staging.git +refs/heads/master:refs/remotes/origin/master

ERROR: Error cloning remote repo 'origin'

hudson.plugins.git.GitException: Command "git fetch --no-tags --progress https://github.com/fharris/environment-wingmisty-staging.git +refs/heads/master:refs/remotes/origin/master" returned status code 128:

stdout: 

stderr: fatal: unable to access 'https://github.com/fharris/environment-wingmisty-staging.git/': Could not resolve host: github.com

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2016)

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1735)

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:72)

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:420)

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:629)

	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1146)

	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1186)

	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:113)

	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:144)

	at org.jenkinsci.plugins.workflow.multibranch.SCMBinder.create(SCMBinder.java:120)

	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:303)

	at hudson.model.ResourceController.execute(ResourceController.java:97)

	at hudson.model.Executor.run(Executor.java:429)

ERROR: Error cloning remote repo 'origin'

Could not update commit status, please check if your scan credentials belong to a member of the organization or a collaborator of the repository and repo:status scope is selected

GitHub has been notified of this commit’s build result

ERROR: Maximum checkout retry attempts reached, aborting

Finished: FAILURE

**Comment by fharris** [comment]
This is a jenkins network issue. Closing the issue. Thanks

**Comment by Damien9527** [comment]
@fharris, Hi,     I met this problem too , Did you solved it ?

**Comment by shravanrai** [comment]
Any solution for this?
