### ISSUE TITLE
Error building PR when using git lfs

### ISSUE THREAD

**Issue by josiahp** [jenkins-x/jx#2245]
### Summary 

In the case of PR builds, repositories using Git LFS (Large File Support) fail to build as Git LFS is not included in the jenkins master image. We are using Bitbucket Server.

In order to workaround the lack of git lfs, I created a custom jnlp image and referenced it in my Jenkinsfile directly. This successfully resolved the issue in the case of branch builds, but in the case of PR builds, the merge is executed on the master before the Jenkinsfile agent is executed.

### Jenkins Error Console Output

```
Branch indexing
Checking out git https://HOST/bitbucket/scm/PROJECT/REPO.git https://HOST/bitbucket/scm/PROJECT/REPO.git into /var/jenkins_home/workspace/REPO_PR-320-5BTUMG5VFYVUGCDGTPEJF2IYR3HY2LV5W2VT4F3OO5LPWECSPLXA@script to read Jenkinsfile
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from 2 remote Git repositories
 > git config remote.origin.url https://HOST/bitbucket/scm/PROJECT/REPO.git # timeout=10
Cleaning workspace
 > git rev-parse --verify HEAD # timeout=10
Resetting working tree
 > git reset --hard # timeout=10
 > git clean -fdx # timeout=10
Fetching without tags
Fetching upstream changes from https://HOST/bitbucket/scm/PROJECT/REPO.git
 > git --version # timeout=10
using GIT_ASKPASS to set credentials Bitbucket server credentials
 > git fetch --no-tags --progress https://HOST/bitbucket/scm/PROJECT/REPO.git +refs/pull-requests/320/from:refs/remotes/origin/PR-320
 > git config remote.upstream.url https://HOST/bitbucket/scm/PROJECT/REPO.git # timeout=10
Cleaning workspace
 > git rev-parse --verify HEAD # timeout=10
Resetting working tree
 > git reset --hard # timeout=10
 > git clean -fdx # timeout=10
Fetching without tags
Fetching upstream changes from https://HOST/bitbucket/scm/PROJECT/REPO.git
using GIT_ASKPASS to set credentials Bitbucket server credentials
 > git fetch --no-tags --progress https://HOST/bitbucket/scm/PROJECT/REPO.git +refs/heads/master:refs/remotes/upstream/master
Merging remotes/upstream/master commit b704ea56a23274eb7506b55afa74abf1254f7005 into PR head commit b7e22012b6e31a862af1373d10d9855fe3018624
Enabling Git LFS pull
 > git config core.sparsecheckout # timeout=10
 > git checkout -f b7e22012b6e31a862af1373d10d9855fe3018624
 > git config --get remote.origin.url # timeout=10
using GIT_ASKPASS to set credentials Bitbucket server credentials
 > git lfs pull origin
[Bitbucket] Notifying pull request build result
[Bitbucket] Build result notified
hudson.plugins.git.GitException: Command "git lfs pull origin" returned status code 1:
stdout: 
stderr: git: 'lfs' is not a git command. See 'git --help'.

Did you mean this?
	log

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2016)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1735)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:72)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$9.execute(CliGitAPIImpl.java:2327)
Caused: hudson.plugins.git.GitException: Could not checkout b7e22012b6e31a862af1373d10d9855fe3018624
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$9.execute(CliGitAPIImpl.java:2339)
	at jenkins.plugins.git.MergeWithGitSCMExtension.checkout(MergeWithGitSCMExtension.java:146)
	at jenkins.plugins.git.MergeWithGitSCMExtension.decorateRevisionToBuild(MergeWithGitSCMExtension.java:112)
	at hudson.plugins.git.GitSCM.determineRevisionToBuild(GitSCM.java:1094)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1187)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:113)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:144)
	at org.jenkinsci.plugins.workflow.multibranch.SCMBinder.create(SCMBinder.java:120)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:303)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Finished: FAILURE
```

### Steps to reproduce the behavior

1. Add a repository to Jenkins that requires git lfs
2. Enable 'Git LFS pull after checkout' on the repository
3. Create a pull request

### Jx version

The output of `jx version` is:

```
$ jx version
Using helmBinary helm with feature flag: none
NAME               VERSION
jx                 1.3.474
jenkins x platform 0.0.2788
Kubernetes cluster v1.9.7-gke.7
kubectl            v1.10.7
helm client        v2.11.0+g2e55dbe
helm server        v2.11.0+g2e55dbe
git                git version 2.11.0
```

### Kubernetes cluster

This is running on GKE, and the cluster was created with terraform.

### Operating system / Environment

Google Cloud Shell

### Expected behavior

`git lfs` should execute without errors.

### Actual behavior

`git lfs` is not installed in the master image.

**Comment by gyorgynadaban** [comment]
This seems to be an issue even if you create a downstream Jenkins master image which does have git-lfs installed.

Tried with this:
```Dockerfile
FROM jenkins/jenkins:2.170

# Use root for install
USER root
RUN curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
RUN apt-get update && apt-get install -y git-lfs

# Drop back to the regular jenkins user
USER jenkins
```

**Comment by pdodds** [comment]
Not really a great solution but I believe you can do

```
yum install -y git-lfs
git lfs pull
```
In your build to get around it.

**Comment by njtman** [comment]
@pdodds No you cannot run this in your build pipeline.  Jenkins master will first perform the checkout locally (for PR branches) before the `Jenkinsfile` is even read, so any commands inside the `Jenkinsfile` will not help us at this point.  In fact, `Jenkins master` performs this checkout for the sole purpose of reading the `Jenkinsfile`.  In a more recent update to the `multi-branch` plugin, the default behavior is for `Jenkins master` to perform a `lightweight checkout` which eliminates the need to perform a full clone, just to obtain the `Jenkinsfile`.  That said, if for whatever reason the lightweight clone cannot be completed, it will fall back to the full clone which will cause the PR build to fail if `git-lfs` is not present on `Jenkins master`.

The only way I've found around this issue is to maintain my own custom Jenkins master image which includes `git-lfs`.
