### ISSUE TITLE
`jx create cluster jx` fails abysmally with UTF-8 codepage.

### ISSUE THREAD

**Issue by jtnord** [jenkins-x/jx#226]
WHen the command prompt (windows) is set to UTF-8 codepage the cluster creation bombs.

```
C:\Users\jnord>jx create cluster gke
Traceback (most recent call last):
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\bundledpython\lib\logging\__init__.py", line 872, in emit
    stream.write(ufs % msg)
LookupError: unknown encoding: cp65001
Logged from file crash_handling.py, line 151
Traceback (most recent call last):
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\lib\gcloud.py", line 88, in <module>
    main()
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\lib\gcloud.py", line 84, in main
    sys.exit(gcloud_main.main())
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\lib\googlecloudsdk\gcloud_main.py", line 162, in main
    crash_handling.HandleGcloudCrash(err)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\lib\googlecloudsdk\command_lib\crash_handling.py", line 153, in HandleGcloudCrash
    log.err.Print('\nIf you would like to report this issue, please run the '
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\lib\googlecloudsdk\core\log.py", line 164, in Print
    self.write(message + u'\n')
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\lib\googlecloudsdk\core\log.py", line 181, in write
    stream_msg = msg.encode(self.encoding or 'utf8', 'replace')
LookupError: unknown encoding: cp65001
Error: Command failed  gcloud auth login --brief
error creating cluster exit status 1
error: exit status 1
```

to reproduce start a `cmd.exe` and change the codepage to UTF-8 (`chcp 65001`) then run `jx create cluster gke`

**Comment by ndeloof** [comment]
Can you please confirm `gcloud auth login --brief`  from such a cp65001 shell works without such an issue ?

**Comment by jtnord** [comment]
`gcloud auth login --brief `fails.

**Comment by jtnord** [comment]
upstream: https://issuetracker.google.com/issues/73334498

**Comment by ccojocar** [comment]
@jtnord Is this still an issue? Can we close it?

**Comment by jtnord** [comment]
the upstream issue is still open - so i guess yes it is still an issue.
