### ISSUE TITLE
random failure creating GKE cluster on windows

### ISSUE THREAD

**Issue by jtnord** [jenkins-x/jx#228]
When the cluster was being prepared I either pressed enter or selected some text to paste (which on windows pauses the output).

This was met with a big stacktrace

```
WARNING: Starting in Kubernetes v1.10, new clusters will no longer get compute-rw and storage-ro scopes added to what is specified in --scopes (though the latter will remain included in the default --scopes). To use these scopes, add them explicitly to --scopes. To use the new behavior, set container/new_scopes_behavior property (gcloud config set container/new_scopes_behavior true).
Exception in thread Thread-1:../
Traceback (most recent call last):
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\bundledpython\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\bundledpython\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\lib\googlecloudsdk\core\console\progress_tracker.py", line 85, in Ticker
    if self.Tick():
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\lib\googlecloudsdk\core\console\progress_tracker.py", line 103, in Tick
    self._Print(_SPIN_MARKS[self._ticks % len(_SPIN_MARKS)])
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\lib\googlecloudsdk\core\console\progress_tracker.py", line 158, in _Print
    sys.stderr.write('\r' + console_width * ' ')
IOError: [Errno 0] Error
```

**Comment by mrlov** [comment]
Does the problem appears only when the GKE cluster master runs on windows? If so, then I would like to try to start with a cluster with linux master and some windows nodes.
Or appears this problem as early as one of the nodes is a windows node?

**Comment by jtnord** [comment]
GKE (nor any of the other major managed providers) support windows master or nodes as yet.
