### ISSUE TITLE
Jenkins X not running executor pods

### ISSUE THREAD

**Issue by lklacar** [jenkins-x/jx#2322]
### Summary 
I'm using microk8s cluster. Jenkins X installation finished fine, no errors. Jenkins is even accessible publicly on http://jenkins.jx.devlab.rs. Installing jx created staging and production repositories on github, and created folder and projects in jenkins. Repository scan also completed without any problems. But for some reason, environment builds are stuck on "Waiting for next available executor".

Running "kubectl get all --all-namespaces shows all pods in running state, but there are no maven pods.
Running "jx status" gives the following output:
```
Jenkins X checks passed for Cluster(microk8s-cluster): 1 nodes, memory 38% of 3527144Ki, cpu 28% of 4. Jenkins is running at http://jenkins.jx.devlab.rs
```
There is an exception shown when running "jx logs jenkins"
```
Nov 24, 2018 12:07:56 PM hudson.slaves.NodeProvisioner$2 run
INFO: Kubernetes Pod Template provisioning successfully completed. We have now 2 computer(s)
Nov 24, 2018 12:07:56 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud provision
INFO: Excess workload after pending Kubernetes agents: 1
Nov 24, 2018 12:07:56 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud provision
INFO: Template for label jenkins-maven: Kubernetes Pod Template
Nov 24, 2018 12:07:56 PM hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
INFO: Started provisioning Kubernetes Pod Template from kubernetes with 1 executors. Remaining excess workload: 0.993
Nov 24, 2018 12:07:56 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher launch
WARNING: Error in provisioning; agent=KubernetesSlave name: maven-zdm1s, template=PodTemplate{inheritFrom='', name='maven', slaveConnectTimeout=0, label='jenkins-maven', serviceAccount='jenkins', nodeSelector='', volumes=[HostPathVolume [mountPath=/var/run/docker.sock, hostPath=/var/run/docker.sock], SecretVolume [mountPath=/root/.m2/, secretName=jenkins-maven-settings], SecretVolume [mountPath=/home/jenkins/.docker, secretName=jenkins-docker-cfg], SecretVolume [mountPath=/home/jenkins/.gnupg, secretName=jenkins-release-gpg]], containers=[ContainerTemplate{name='jnlp', image='jenkinsci/jnlp-slave:3.26-1-alpine', workingDir='/home/jenkins', command='', args='${computer.jnlpmac} ${computer.name}', resourceRequestCpu='100m', resourceRequestMemory='128Mi', resourceLimitCpu='', resourceLimitMemory=''}, ContainerTemplate{name='maven', image='jenkinsxio/builder-maven:0.1.88', privileged=true, workingDir='/home/jenkins', command='/bin/sh -c', args='cat', ttyEnabled=true, resourceRequestCpu='400m', resourceRequestMemory='512Mi', resourceLimitCpu='1', resourceLimitMemory='1024Mi'}], envVars=[ContainerEnvVar [getValue()=/home/jenkins/.docker/, getKey()=DOCKER_CONFIG], ContainerEnvVar [getValue()=jenkins-x@googlegroups.com, getKey()=GIT_AUTHOR_EMAIL], ContainerEnvVar [getValue()=jenkins-x-bot, getKey()=GIT_AUTHOR_NAME], ContainerEnvVar [getValue()=jenkins-x@googlegroups.com, getKey()=GIT_COMMITTER_EMAIL], ContainerEnvVar [getValue()=jenkins-x-bot, getKey()=GIT_COMMITTER_NAME], ContainerEnvVar [getValue()=http://jenkins:8080, getKey()=JENKINS_URL], ContainerEnvVar [getValue()=/home/jenkins, getKey()=XDG_CONFIG_HOME], ContainerEnvVar [getValue()=-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Xms10m -Xmx192m, getKey()=_JAVA_OPTIONS]]}
io.fabric8.kubernetes.client.KubernetesClientException: Operation: [create]  for kind: [Pod]  with name: [null]  in namespace: [jx]  failed.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:62)
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:71)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:342)
	at org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher.launch(KubernetesLauncher.java:105)
	at hudson.slaves.SlaveComputer$1.call(SlaveComputer.java:294)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: KeyUsage does not allow digital signatures
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1964)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:328)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:322)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1614)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1052)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:987)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:299)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:268)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:160)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:256)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:134)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:113)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at io.fabric8.kubernetes.client.utils.BackwardsCompatibilityInterceptor.intercept(BackwardsCompatibilityInterceptor.java:104)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at io.fabric8.kubernetes.client.utils.ImpersonatorInterceptor.intercept(ImpersonatorInterceptor.java:56)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at io.fabric8.kubernetes.client.utils.HttpClientUtils$2.intercept(HttpClientUtils.java:107)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall.execute(RealCall.java:77)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:379)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:344)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:227)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:766)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:335)
	... 8 more
Caused by: sun.security.validator.ValidatorException: KeyUsage does not allow digital signatures
	at sun.security.validator.EndEntityChecker.checkTLSServer(EndEntityChecker.java:271)
	at sun.security.validator.EndEntityChecker.check(EndEntityChecker.java:143)
	at sun.security.validator.Validator.validate(Validator.java:274)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1596)
	... 48 more

Nov 24, 2018 12:07:56 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave _terminate
INFO: Terminating Kubernetes instance for agent maven-zdm1s
```

### Steps to reproduce the behavior
I used the following commands to install the cluster and install jenkins x, so this is basically a clean install:
https://github.com/lklacar/microk8s-jenkins-x-setup
### Jx version

The output of `jx version` is:

```
jx                 1.3.589
jenkins x platform 0.0.2934
Kubernetes cluster v1.12.2
kubectl            v1.12.2
helm client        v2.11.0+g2e55dbe
helm server        v2.11.0+g2e55dbe
git                git version 2.19.1
Operating System   "Fedora release 29 (Twenty Nine)"

```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?
I'm using microk8s cluster installed on a separate PC I got laying around.\
I installed everything by using these commands:
https://github.com/lklacar/microk8s-jenkins-x-setup

### Operating system / Environment
Cluster is running on Ubuntu Server 18.10
I'm accessing the cluster with kubectl running on Fedora 29
### Expected behavior
I would expect everything to work, since its a clean install.
### Actual behavior
Jenkins X executor pods are not running and an exception is shown.

**Comment by ccojocar** [comment]
@lklacar I looks like a problem with your cluster. It seems to me that the kuberntes api-server cert/key are not properly configured on the node where the Jenkins is running, and therefore it cannot access the api server to create new build pods. 

You can try the `install` command with a Kubernetes provided by GKE/AWS(EKS or kops). 

I am going to close this issue since is not really in `jx`.
