### ISSUE TITLE
Error running jx create docker auth command

### ISSUE THREAD

**Issue by virtualorg1** [jenkins-x/jx#2380]
### Summary 
Running 'jx create docker auth' produces an error and fails to work
### Steps to reproduce the behavior
Running:  jx create docker auth --host 'fra.ocir.io' --user 'xxxxx' --secret 'xxxxxxxxxx' --email 'xxxxxxxxx' as well as just running 'jx create docker auth' with no parameters, or just 'jx create docker' without 'auth' all fail with error shown below.
### Jx version

The output of `jx version` is:

```
1.3.212

```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?
It is an Oracle Cloud Infrastructure Kubernetes Engine (OKE). Created using: 

jx install --provider=kubernetes --external-ip [External/LoadBalancer IP] --ingress-service=nginx-nginx-ingress-controller --ingress-deployment=nginx-nginx-ingress-controller --ingress-namespace=kube-system

Cluster seems to be working fine and all other jx functionality seems fine. Just pushing a container to the registry is having a problem because it doesn't have the credentials.

### Operating system / Environment
Oracle Linux Server release 7.5

### Expected behavior
Should add credentials secret to jenkins-docker-cfg
### Actual behavior
Running:

 jx create docker auth --host 'fra.ocir.io' --user 'xxxxx' --secret 'xxxxxxxxxx' --email 'xxxxxxxxx' as well as just running 'jx create docker auth' with no parameters, or just 'jx create docker' without 'auth' all fail with the following error:

panic: unable to redefine 'h' shorthand in "docker" flagset: it's already used for "host" flag

goroutine 1 [running]:
github.com/jenkins-x/jx/vendor/github.com/spf13/pflag.(*FlagSet).AddFlag(0xc000204600, 0xc0009408c0)
	/home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/spf13/pflag/flag.go:862 +0x6e5
github.com/jenkins-x/jx/vendor/github.com/spf13/pflag.(*FlagSet).VarPF(0xc000204600, 0x27e1d20, 0xc000634e77, 0x249934f, 0x4, 0x2497db8, 0x1, 0xc000634e80, 0xf, 0xc000634e77)
	/home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/spf13/pflag/flag.go:819 +0x10b
github.com/jenkins-x/jx/vendor/github.com/spf13/pflag.(*FlagSet).BoolVarP(0xc000204600, 0xc000634e77, 0x249934f, 0x4, 0x2497db8, 0x1, 0x0, 0xc000634e80, 0xf)
	/home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/spf13/pflag/bool.go:55 +0x97
github.com/jenkins-x/jx/vendor/github.com/spf13/pflag.(*FlagSet).BoolP(0xc000204600, 0x249934f, 0x4, 0x2497db8, 0x1, 0xc000634e00, 0xc000634e80, 0xf, 0x5)
	/home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/spf13/pflag/bool.go:80 +0x9a
github.com/jenkins-x/jx/vendor/github.com/spf13/cobra.(*Command).InitDefaultHelpFlag(0xc0000f1680)
	/home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/spf13/cobra/command.go:914 +0x136
github.com/jenkins-x/jx/vendor/github.com/spf13/cobra.(*Command).execute(0xc0000f1680, 0xc00045d800, 0x8, 0x8, 0xc0000f1680, 0xc00045d800)
	/home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/spf13/cobra/command.go:686 +0x57
github.com/jenkins-x/jx/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0005b2f00, 0xc00050a000, 0xc000607680, 0xc000512780)
	/home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/jenkins-x/jx/vendor/github.com/spf13/cobra.(*Command).Execute(0xc0005b2f00, 0xc0000b8a60, 0x27cc3a0)
	/home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/jenkins-x/jx/cmd/jx/app.Run(0xc000a01f88, 0xc00008c058)
	/home/jenkins/go/src/github.com/jenkins-x/jx/cmd/jx/app/jx.go:17 +0x90
main.main()
	/home/jenkins/go/src/github.com/jenkins-x/jx/cmd/jx/jx.go:10 +0x22
[holuser@docker .jx]$ cd /home/jenkins/.docker/

**Comment by virtualorg1** [comment]
Just installed latest version of jx, version 1.3.613 and it now works.
