### ISSUE TITLE
running BDD test get panic in jx createChromeDPLogger

### ISSUE THREAD

**Issue by rawlingsj** [jenkins-x/jx#251]
Intermittently getting a panic running the BDD tests on GKE, not too sure what it is yet so raising to track, seems to be coming from here https://github.com/jenkins-x/jx/blob/master/pkg/jx/cmd/create_jenkins_token.go#L306

```
Trying to generate an API token for user: testuser
Chrome debugging logs written to: /tmp/jx-browser574672148
Creating a screenshot...
logging in
Creating a screenshot...
EXITCODE   0panic: runtime error: slice bounds out of range

goroutine 45 [running]:
bufio.(*Writer).Write(0xc4201f61c0, 0xc423545000, 0x51, 0x200, 0x1, 0x1, 0xc420048da0)
	/Users/jr/bin/go/src/bufio/bufio.go:601 +0x264
fmt.Fprintf(0x2138de0, 0xc4201f61c0, 0xc420048de8, 0x6, 0xc4238f86d0, 0x1, 0x1, 0x1069382, 0xc420048e10, 0x40e3ef)
	/Users/jr/bin/go/src/fmt/print.go:182 +0xa5
github.com/jenkins-x/jx/pkg/jx/cmd.(*CommonOptions).createChromeDPLogger.func2(0x16e34e8, 0x5, 0xc4238f86d0, 0x1, 0x1)
	/Users/jr/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/create_jenkins_token.go:306 +0xbf
github.com/jenkins-x/jx/vendor/github.com/chromedp/chromedp.(*TargetHandler).read(0xc420438420, 0x0, 0x0, 0x0)
	/Users/jr/go/src/github.com/jenkins-x/jx/vendor/github.com/chromedp/chromedp/handler.go:212 +0x12a
github.com/jenkins-x/jx/vendor/github.com/chromedp/chromedp.(*TargetHandler).run.func1(0xc420232080, 0xc420438420, 0x215ba60, 0xc42026ab80)
	/Users/jr/go/src/github.com/jenkins-x/jx/vendor/github.com/chromedp/chromedp/handler.go:151 +0x15e
created by github.com/jenkins-x/jx/vendor/github.com/chromedp/chromedp.(*TargetHandler).run
	/Users/jr/go/src/github.com/jenkins-x/jx/vendor/github.com/chromedp/chromedp/handler.go:145 +0x109
make: *** [create-gitea] Error 2
```

**Comment by rawlingsj** [comment]
this doesn't happen anymore
