### ISSUE TITLE
knative-build-bot cannot list customresourcedefinitions.apiextensions.k8s.io at the cluster scope

### ISSUE THREAD

**Issue by jglick** [jenkins-x/jx#2833]
### Summary 

Builds in our dev cluster are showing warnings from the `jx-resources` plugin beginning with

```
WARNING	i.f.k.c.i.VersionUsageUtils#alert: The client is using resource type 'customresourcedefinitions' with unstable version 'v1beta1'
SEVERE	hudson.triggers.SafeTimerTask#run: Timer task org.jenkinsci.plugins.jx.resources.BuildSyncRunListener$1@… failed
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://kubernetes.default.svc/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. customresourcedefinitions.apiextensions.k8s.io is forbidden: User "system:serviceaccount:jx:knative-build-bot" cannot list customresourcedefinitions.apiextensions.k8s.io at the cluster scope.
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:472)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:409)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:381)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:344)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:328)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:584)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:49)
	at io.jenkins.x.client.kube.ClientHelper.pipelineActivityClient(ClientHelper.java:21)
	at org.jenkinsci.plugins.jx.resources.BuildSyncRunListener.upsertBuild(BuildSyncRunListener.java:244)
	at org.jenkinsci.plugins.jx.resources.BuildSyncRunListener.pollRun(BuildSyncRunListener.java:214)
	at org.jenkinsci.plugins.jx.resources.BuildSyncRunListener.pollLoop(BuildSyncRunListener.java:202)
	at org.jenkinsci.plugins.jx.resources.BuildSyncRunListener$1.doRun(BuildSyncRunListener.java:166)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:72)
	at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:58)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### Steps to reproduce the behavior

Unclear; appears while running `bdd-jx` tests. (@snoopdave may have details.)

### Expected behavior

No warnings.

### Actual behavior

See above.

### Jx version

The output of `jx version` includes:

```
jenkins x platform 0.0.3275
Kubernetes cluster v1.11.5-gke.5
```

The output of `jx get addons` includes:

```
jx-build-templates jenkins-x/jx-build-templates          DEPLOYED 0.0.376
jx-prow            jenkins-x/prow                        DEPLOYED 0.0.135
knative-build      jenkins-x/knative-build               DEPLOYED 0.1.4
```

### Jenkins type

- [ ] Classic Jenkins
- [X] Serverless Jenkins

### Kubernetes cluster

GKE

**Comment by jglick** [comment]
Preliminary investigation:

The RBAC looks OK to me (though `0.1.12` does not match `0.1.4`; maybe something else?):

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations: …
  creationTimestamp: …
  labels:
    jenkins.io/chart-release: knative-build
    jenkins.io/version: 0.1.12
  name: knative-build-bot
  resourceVersion: …
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/knative-build-bot
  uid: …
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - list
  - create
  - get
  - update
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - get
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
```

The error is apparently coming from the [`jx-resources` plugin](https://github.com/jenkinsci/jx-resources-plugin/blob/963636171d1383cd011f06bc3ebffdbd1f30a4c9/src/main/java/org/jenkinsci/plugins/jx/resources/BuildSyncRunListener.java#L224) via the [`jx-java-client` library](https://github.com/jenkins-x/jx-java-client/blob/e78ede5a34484cb9a77f2134edad2f4bf716252f/src/main/java/io/jenkins/x/client/kube/ClientHelper.java#L21).

**Comment by jglick** [comment]
I think the issue is that the `ClusterRoleBinding` for `knative-build-bot` was given an incorrect `subjects[0].namespace`, presumably a mistake in the BDD tests.

**Comment by jglick** [comment]
…and perhaps fixed by https://github.com/jenkins-x-charts/knative/pull/11.
