### ISSUE TITLE
jx import tries to create existing Jenkins folder, fails

### ISSUE THREAD

**Issue by wbrefvem** [jenkins-x/jx#3007]
### Summary 

When running `jx import --git-provider-url=https://bitbucket.org`, everything works until `jx import` tries to create a folder that already exists in Jenkins, at which point it barfs a series of 500s and fails after the 10th one.

### Steps to reproduce the behavior

Run `jx import` and choose the same git provider and user/org that you used to create your envs.

### Expected behavior

`jx import` should install a multibranch pipeline for the imported project under an existing folder in Jenkins.

### Actual behavior

`jx import` throws a series of 500s and fails.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.839
jenkins x platform 0.0.3354
Kubernetes cluster v1.11.6-gke.2
kubectl            v1.12.0
helm client        v2.11.0+g2e55dbe
helm server        v2.12.2+g7d2b0c7
git                git version 2.17.2 (Apple Git-113)
Operating System   Mac OS X 10.14.2 build 18C54
```

### Jenkins type

- [x] Classic Jenkins
- [ ] Serverless Jenkins

### Kubernetes cluster

GKE, `jx create cluster gke`

### Operating system / Environment
```
ProductName:	Mac OS X
ProductVersion:	10.14.2
BuildVersion:	18C54
```

**Comment by polothy** [comment]
Running into the same problem, trying to debug it... any tips would be appreciated!

**Comment by polothy** [comment]
So, I re-created the request via curl:
```
curl -v -H "Authorization: Basic base64encodedauth" https://myserver.com/job/FOLDER/api/json
```

And that returns a `HTTP/1.1 500 Server Error` with some HTML:
```
A problem occurred while processing the request. Please check our bug tracker to see if a similar problem has already been reported. If it is already reported, please vote and put a comment on it to let us gauge the impact of the problem. If you think this is a new issue, please file a new issue. When you file an issue, make sure to add the entire stack trace, along with the version of Jenkins and relevant plugins. The users list might be also useful in understanding what has happened.

Stack trace

hudson.security.AccessDeniedException2: anonymous is missing the Overall/Read permission
        at hudson.security.ACL.checkPermission(ACL.java:73)
        at hudson.security.AccessControlled.checkPermission(AccessControlled.java:47)
        at jenkins.model.Jenkins.getTarget(Jenkins.java:4675)
        at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:695)
        at org.kohsuke.stapler.Stapler.invoke(Stapler.java:870)
        at org.kohsuke.stapler.Stapler.invoke(Stapler.java:668)
        at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:566)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
        at org.eclipse.jetty.server.Dispatcher.include(Dispatcher.java:124)
        at hudson.security.BasicAuthenticationFilter.doFilter(BasicAuthenticationFilter.java:170)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:90)
        at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
        at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
        at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
        at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:503)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
        at java.lang.Thread.run(Thread.java:748)
```

And really the problem was that my admin API Token was no longer valid.  I removed it from `~/.jx/jenkinsAuth.yaml` and JX prompted me to create a new one.  After that, it worked fine.

Would be nice if Jenkins would return an authorization error instead of 500.

**Comment by deanesmith** [comment]
Hi @wbrefvem, We are closing this issue because static Jenkins masters have been deprecated and removed from Jenkins X in favor of focusing on Tekton pipelines.

This blog has more information as to the reasons why: https://jenkins-x.io/blog/2020/03/11/tekton/

If you’d like to discuss this in more detail, please join our Jenkins X channels in the Kubernetes Slack and tag any of our product leadership (Deane Smith, Viktor Farcic, Ethan Jones, Dave Conde, James Rawlings, James Strachan) and we’d be happy to discuss further. 

If this is a surprise to you, consider joining the Jenkins X newsletter and other community channels to make sure that important notices like this always make it to you: https://jenkins-x.io/community/ https://jenkins-x.io/community/
