### ISSUE TITLE
panic in edit userrole

### ISSUE THREAD

**Issue by jtnord** [jenkins-x/jx#3723]
### Summary 

it is possible to panic jx in the edit userrole command.

### Steps to reproduce the behavior

* `jx edit userrole`
* type something that does not match
* press the up arrow key

### Expected behavior

no panic

### Actual behavior

panic

```
 ☸ plat-shared-rbac:myfirstteam  master  C:\Users\jnord\go\src\github.com\cloudbees\core-backend>jx edit userrole
? Pick the user to edit wibble  [Use arrows to move, space to select, type to filter]
panic: runtime error: index out of range

goroutine 1 [running]:
gopkg.in/AlecAivazis/survey%2ev1.(*Select).OnChange(0xc0008b7ba0, 0x0, 0x0, 0x0, 0x0, 0x10, 0x804f8d0, 0x0, 0x0, 0x0, ...)
        /home/jenkins/go/pkg/mod/gopkg.in/!alec!aivazis/survey.v1@v1.8.3/select.go:152 +0x6c1
gopkg.in/AlecAivazis/survey%2ev1.(*Select).Prompt(0xc0008b7ba0, 0x0, 0x0, 0x0, 0x0)
        /home/jenkins/go/pkg/mod/gopkg.in/!alec!aivazis/survey.v1@v1.8.3/select.go:232 +0x34d
gopkg.in/AlecAivazis/survey%2ev1.Ask(0xc000ed9838, 0x1, 0x1, 0x352cfe0, 0xc00026c9e0, 0xc000ed98a8, 0x1, 0x1, 0xa3f088, 0x39572e0)
        /home/jenkins/go/pkg/mod/gopkg.in/!alec!aivazis/survey.v1@v1.8.3/survey.go:148 +0x191
gopkg.in/AlecAivazis/survey%2ev1.AskOne(0x46024a0, 0xc0008b7ba0, 0x352cfe0, 0xc00026c9e0, 0x0, 0xc000ed98a8, 0x1, 0x1, 0x0, 0x0)
        /home/jenkins/go/pkg/mod/gopkg.in/!alec!aivazis/survey.v1@v1.8.3/survey.go:94 +0xd4
github.com/jenkins-x/jx/pkg/util.PickNameWithDefault(0xc000935c80, 0x2, 0x2, 0x3e59ea4, 0x15, 0x0, 0x0, 0x0, 0x0, 0x45f7860, ...)
        /workspace/source/pkg/util/pickers.go:64 +0x200
github.com/jenkins-x/jx/pkg/util.PickName(0xc000935c80, 0x2, 0x2, 0x3e59ea4, 0x15, 0x0, 0x0, 0x45f7860, 0xc0000bc000, 0x45f78a0, ...)
        /workspace/source/pkg/util/pickers.go:97 +0xeb
github.com/jenkins-x/jx/pkg/jx/cmd.(*EditUserRoleOptions).Run(0xc00040fda0, 0x0, 0x0)
        /workspace/source/pkg/jx/cmd/edit_userrole.go:107 +0x23a
github.com/jenkins-x/jx/pkg/jx/cmd.NewCmdEditUserRole.func1(0xc0005dec80, 0x804f8d0, 0x0, 0x0)
        /workspace/source/pkg/jx/cmd/edit_userrole.go:59 +0x76
github.com/spf13/cobra.(*Command).execute(0xc0005dec80, 0x804f8d0, 0x0, 0x0, 0xc0005dec80, 0x804f8d0)
        /home/jenkins/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2d3
github.com/spf13/cobra.(*Command).ExecuteC(0xc00039b400, 0xc0006a7b80, 0xc0005d9180, 0xc0006c4280)
        /home/jenkins/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x304
github.com/spf13/cobra.(*Command).Execute(0xc00039b400, 0xc00023a9b0, 0x45f7860)
        /home/jenkins/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800 +0x32
github.com/jenkins-x/jx/cmd/jx/app.Run(0xc000681f88, 0xc000086058)
        /workspace/source/cmd/jx/app/jx-win.go:17 +0xf9
main.main()
        /workspace/source/cmd/jx/jx.go:11 +0x29

```
### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.37
jenkins x platform 0.0.3321
Kubernetes cluster v1.12.6-gke.10
kubectl            v1.13.0
helm client        Client: v2.11.0+g2e55dbe
git                git version 2.16.2.windows.1
Operating System   Windows 10 Pro 1809 build 17763
```

### Jenkins type

- [ ] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

**Comment by jtnord** [comment]
https://github.com/AlecAivazis/survey/issues/189
