### ISSUE TITLE
jx import: support creating repositories in local BitBucket server / enterprise repos

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#38]

**Comment by aairey** [comment]
Think I may have opened [this issue](https://issues.jenkins-ci.org/browse/JENKINS-54147) on the wrong project (?).

Anyhow, I tried `jx import` on a project yesterday and it got up to the point of creating the multibranch job on Jenkins.
However it could not scan the BitBucket project / repository - showing the following output:
```
[Thu Oct 18 16:07:27 UTC 2018] Starting branch indexing...
ERROR: [Thu Oct 18 16:07:27 UTC 2018] Could not update folder level actions from source f82b5bae-d2eb-11e8-891f-28f10e15fb27
org.apache.http.HttpException: ssh protocol is not supported
	at org.apache.http.impl.conn.DefaultRoutePlanner.determineRoute(DefaultRoutePlanner.java:89)
	at org.apache.http.impl.client.InternalHttpClient.determineRoute(InternalHttpClient.java:125)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
Caused: org.apache.http.client.ClientProtocolException
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:187)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getRequest(BitbucketServerAPIClient.java:655)
Caused: java.io.IOException: Communication error for url: /rest/api/1.0/projects/dms/repos/dms
	at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getRequest(BitbucketServerAPIClient.java:685)
	at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getRepository(BitbucketServerAPIClient.java:363)
	at com.cloudbees.jenkins.plugins.bitbucket.BitbucketSCMSource.retrieveActions(BitbucketSCMSource.java:1068)
	at jenkins.scm.api.SCMSource.fetchActions(SCMSource.java:748)
	at jenkins.branch.MultiBranchProject.computeChildren(MultiBranchProject.java:590)
	at com.cloudbees.hudson.plugins.folder.computed.ComputedFolder.updateChildren(ComputedFolder.java:276)
	at com.cloudbees.hudson.plugins.folder.computed.FolderComputation.run(FolderComputation.java:165)
	at jenkins.branch.MultiBranchProject$BranchIndexing.run(MultiBranchProject.java:1024)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
[Thu Oct 18 16:07:27 UTC 2018] Finished branch indexing. Indexing took 0.27 sec
FATAL: Failed to recompute children of dms » dms
java.io.IOException: Communication error for url: /rest/api/1.0/projects/dms/repos/dms
	at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getRequest(BitbucketServerAPIClient.java:685)
	at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getRepository(BitbucketServerAPIClient.java:363)
	at com.cloudbees.jenkins.plugins.bitbucket.BitbucketSCMSource.retrieveActions(BitbucketSCMSource.java:1068)
	at jenkins.scm.api.SCMSource.fetchActions(SCMSource.java:748)
	at jenkins.branch.MultiBranchProject.computeChildren(MultiBranchProject.java:590)
	at com.cloudbees.hudson.plugins.folder.computed.ComputedFolder.updateChildren(ComputedFolder.java:276)
	at com.cloudbees.hudson.plugins.folder.computed.FolderComputation.run(FolderComputation.java:165)
	at jenkins.branch.MultiBranchProject$BranchIndexing.run(MultiBranchProject.java:1024)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Caused by: org.apache.http.client.ClientProtocolException
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:187)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getRequest(BitbucketServerAPIClient.java:655)
	... 9 more
Caused by: org.apache.http.HttpException: ssh protocol is not supported
	at org.apache.http.impl.conn.DefaultRoutePlanner.determineRoute(DefaultRoutePlanner.java:89)
	at org.apache.http.impl.client.InternalHttpClient.determineRoute(InternalHttpClient.java:125)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	... 11 more
Finished: FAILURE 
```
Only later I found this issue where it is clear it is not yet fully supported.
If there is anything I can do to help (maybe run a test version of jx), let me know.

PS: the link from the roadmap links to the bitbucket**.org** issue (#36).

**Comment by ccojocar** [comment]
@wbrefvem Can we close this issue? Are the repositories created? Thanks

**Comment by aairey** [comment]
This is related to ssh not being implemented as checkout method.
Haven't tried Jenkins X since as it was blocking us, so not sure if this functionality is now there?

**Comment by wbrefvem** [comment]
@aairey There have been some issues related to Bitbucket and `jx import`, but it should be working now. Do you mind giving it a spin and telling us what you find? You can either raise a new issue or ping me on Slack. (https://jenkins-x.io/community/ for Slack info)

@ccojocar Yeah, I'm going to go head and close it.
