### ISSUE TITLE
API Token url cannot access

### ISSUE THREAD

**Issue by YuTingLiu** [jenkins-x/jx#4731]
### Summary 
The http://DOMIN/me/configure can not visit.

### Steps to reproduce the behavior
1. `jx install  --provider=aws --ingress-service=istio-ingressgateway --ingress-deployment=istio-ingressgateway --ingress-namespace=istio-system --ingress-service=istio-ingressgateway --git-provider-url https://bitbucket.org --cleanup-temp-files=false --skip-ingress=true --skip-cluster-role=true`
2. `kubectl apply -f gateway.yaml`

3. `curl http://ac.cn-northwest-1.elb.amazonaws.com.cn/jx/me/config --user "admin:PWD"`

### Expected behavior
![image](https://user-images.githubusercontent.com/8286904/61226358-ddb18180-a754-11e9-8f6d-50e29a8ed832.png)

### Actual behavior
` <!DOCTYPE html><html><head resURL="/static/b8e2557c" data-rooturl="" data-resurl="/static/b8e2557c">

    <title>Jenkins [Jenkins]</title><link rel="stylesheet" href="/static/b8e2557c/css/layout-common.css" type="text/css" /><link rel="stylesheet" href="/static/b8e2557c/css/style.css" type="text/css" /><link rel="stylesheet" href="/static/b8e2557c/css/color.css" type="text/css" /><link rel="stylesheet" href="/static/b8e2557c/css/responsive-grid.css" type="text/css" /><link rel="shortcut icon" href="/static/b8e2557c/favicon.ico" type="image/vnd.microsoft.icon" /><link color="black" rel="mask-icon" href="/images/mask-icon.svg" /><script>var isRunAsTest=false; var rootURL=""; var resURL="/static/b8e2557c";</script><script src="/static/b8e2557c/scripts/prototype.js" type="text/javascript"></script><script src="/static/b8e2557c/scripts/behavior.js" type="text/javascript"></script><script src='/adjuncts/b8e2557c/org/kohsuke/stapler/bind.js' type='text/javascript'></script><script src="/static/b8e2557c/scripts/yui/yahoo/yahoo-min.js"></script><script src="/static/b8e2557c/scripts/yui/dom/dom-min.js"></script><script src="/static/b8e2557c/scripts/yui/event/event-min.js"></script><script src="/static/b8e2557c/scripts/yui/animation/animation-min.js"></script><script src="/static/b8e2557c/scripts/yui/dragdrop/dragdrop-min.js"></script><script src="/static/b8e2557c/scripts/yui/container/container-min.js"></script><script src="/static/b8e2557c/scripts/yui/connection/connection-min.js"></script><script src="/static/b8e2557c/scripts/yui/datasource/datasource-min.js"></script><script src="/static/b8e2557c/scripts/yui/autocomplete/autocomplete-min.js"></script><script src="/static/b8e2557c/scripts/yui/menu/menu-min.js"></script><script src="/static/b8e2557c/scripts/yui/element/element-min.js"></script><script src="/static/b8e2557c/scripts/yui/button/button-min.js"></script><script src="/static/b8e2557c/scripts/yui/storage/storage-min.js"></script><script src="/static/b8e2557c/scripts/hudson-behavior.js" type="text/javascript"></script><script src="/static/b8e2557c/scripts/sortable.js" type="text/javascript"></script><script>crumb.init("", "");</script><link rel="stylesheet" href="/static/b8e2557c/scripts/yui/container/assets/container.css" type="text/css" /><link rel="stylesheet" href="/static/b8e2557c/scripts/yui/assets/skins/sam/skin.css" type="text/css" /><link rel="stylesheet" href="/static/b8e2557c/scripts/yui/container/assets/skins/sam/container.css" type="text/css" /><link rel="stylesheet" href="/static/b8e2557c/scripts/yui/button/assets/skins/sam/button.css" type="text/css" /><link rel="stylesheet" href="/static/b8e2557c/scripts/yui/menu/assets/skins/sam/menu.css" type="text/css" /><meta name="ROBOTS" content="INDEX,NOFOLLOW" /><meta name="viewport" content="width=device-width, initial-scale=1" /><script src="/static/b8e2557c/jsbundles/page-init.js" type="text/javascript"></script></head><body data-model-type="hudson.model.Hudson" id="jenkins" class="yui-skin-sam two-column jenkins-2.176.1" data-version="2.176.1"><a href="#skip2content" class="skiplink">Skip to content</a><div id="page-head"><div id="header"><div class="logo"><a id="jenkins-home-link" href="/"><img src="/static/b8e2557c/images/headshot.png" alt="[Jenkins]" id="jenkins-head-icon" /><img src="/static/b8e2557c/images/title.png" alt="Jenkins" width="139" id="jenkins-name-icon" height="34" /></a></div><div class="login"> <a href="/loginEntry?from=%2Fjx%2Fme%2Fconfig"><b>log in</b></a></div><div class="searchbox hidden-xs"><form role="search" method="get" name="search" action="/search/" style="position:relative;" class="no-json"><div id="search-box-minWidth"></div><div id="search-box-sizer"></div><div id="searchform"><input role="searchbox" name="q" placeholder="search" id="search-box" class="has-default-text" /> <a href="https://jenkins.io/redirect/search-box"><img src="/static/b8e2557c/images/16x16/help.png" style="width: 16px; height: 16px; " class="icon-help icon-sm" /></a><div id="search-box-completion"></div><script>createSearchBox("/search/");</script></div></form></div></div><div id="breadcrumbBar"><tr id="top-nav"><td id="left-top-nav" colspan="2"><link rel='stylesheet' href='/adjuncts/b8e2557c/lib/layout/breadcrumbs.css' type='text/css' /><script src='/adjuncts/b8e2557c/lib/layout/breadcrumbs.js' type='text/javascript'></script><div class="top-sticker noedge"><div class="top-sticker-inner"><div id="right-top-nav"></div><ul id="breadcrumbs"><li class="item"><a href="/" class="model-link inside">Jenkins</a></li><li href="/" class="children"></li></ul><div id="breadcrumb-menu-target"></div></div></div></td></tr></div></div><div id="page-body" class="clear"><div id="side-panel"><div class="task"><a href="https://jenkins.io/" class="task-icon-link"><img src="/static/b8e2557c/images/24x24/next.png" style="width: 24px; height: 24px; width: 24px; height: 24px; margin: 2px;" class="icon-next icon-md" /></a> <a href="https://jenkins.io/" class="task-link">Jenkins project</a></div><div class="task"><a href="https://jenkins.io/redirect/report-an-issue" class="task-icon-link"><img src="/static/b8e2557c/images/24x24/gear2.png" style="width: 24px; height: 24px; width: 24px; height: 24px; margin: 2px;" class="icon-gear2 icon-md" /></a> <a href="https://jenkins.io/redirect/report-an-issue" class="task-link">Bug tracker</a></div><div class="task"><a href="https://jenkins.io/redirect/mailing-lists" class="task-icon-link"><img src="/static/b8e2557c/images/24x24/search.png" style="width: 24px; height: 24px; width: 24px; height: 24px; margin: 2px;" class="icon-search icon-md" /></a> <a href="https://jenkins.io/redirect/mailing-lists" class="task-link">Mailing Lists</a></div><div class="task"><a href="https://twitter.com/jenkinsci" class="task-icon-link"><img src="/static/b8e2557c/images/24x24/user.png" style="width: 24px; height: 24px; width: 24px; height: 24px; margin: 2px;" class="icon-user icon-md" /></a> <a href="https://twitter.com/jenkinsci" class="task-link">Twitter: @jenkinsci</a></div></div><div id="main-panel"><a name="skip2content"></a><h1 style="text-align: center"><img src="/static/b8e2557c/images/rage.png" width="154" height="179" /><span style="font-size:50px"> Oops!</span></h1><div id="error-description"><p>A problem occurred while processing the request.
        Please check <a href="https://jenkins.io/redirect/issue-tracker">our bug tracker</a> to see if a similar problem has already been reported.
        If it is already reported, please vote and put a comment on it to let us gauge the impact of the problem.
        If you think this is a new issue, please file a new issue.
        When you file an issue, make sure to add the entire stack trace, along with the version of Jenkins and relevant plugins.
        <a href="https://jenkins.io/redirect/users-mailing-list">The users list</a> might be also useful in understanding what has happened.</p><h2>Stack trace</h2><pre style="margin:2em; clear:both">hudson.security.AccessDeniedException2: anonymous is missing the Overall/Read permission
        at hudson.security.ACL.checkPermission(ACL.java:73)
        at hudson.security.AccessControlled.checkPermission(AccessControlled.java:47)
        at jenkins.model.Jenkins.getTarget(Jenkins.java:4697)
        at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:703)
        at org.kohsuke.stapler.Stapler.invoke(Stapler.java:878)
        at org.kohsuke.stapler.Stapler.invoke(Stapler.java:676)
        at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:873)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:542)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:566)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1701)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1668)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
        at org.eclipse.jetty.server.Dispatcher.include(Dispatcher.java:129)
        at hudson.security.BasicAuthenticationFilter.doFilter(BasicAuthenticationFilter.java:169)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:90)
        at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
        at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
        at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
        at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1701)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1668)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:502)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
        at java.lang.Thread.run(Thread.java:748)
</pre></div></div></div><footer><div class="container-fluid"><div class="row"><div class="col-md-6" id="footer"></div><div class="col-md-18"><span class="page_generated">Page generated: Jul 15, 2019 2:58:30 PM UTC</span><span class="rest_api"><a href="api/">REST API</a></span><span class="jenkins_ver"><a href="https://jenkins.io/">Jenkins ver. 2.176.1</a></span></div></div></div></footer></body></html>`
### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.368
jenkins x platform 2.0.822
Kubernetes cluster v1.12.8
kubectl            v1.12.8
helm client        Client: v2.14.0+g05811b8
git                git version 1.8.3.1
Operating System   CentOS Linux release 7.6.1810 (Core)
WARNING:
A new jx version is available: 2.0.463
? Would you like to upgrade to the new jx version? [? for help] (Y/n)

```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [X ] Classic Jenkins

**Comment by YuTingLiu** [comment]
istio-gateway problem。
