### ISSUE TITLE
Jx promote error: Getting content not supported on Bitbucket

### ISSUE THREAD

**Issue by saahilbhutwala** [jenkins-x/jx#5041]
### Summary 
I am trying to deploy activiti7 cloud application on a GKE Cluster using Jenkins-X CI/CD pipeline and using **BITBUCKET SERVER** as my primary git provider and service. I installed jx on the gke cluster, after which I set up staging and production activiti repos and created a quickstart to get activiti-cloud-application from https://github.com/activiti. The pipeline is built on JX but I recieved an error while promoting to environments at jx promote step.

### Steps to reproduce the behavior

jx create quickstartlocation --owner activiti
Adding the quickstart git owner https://github.com/activiti

jx create quickstart --owner activiti \
>     --filter=activiti-cloud-platform-quickstart \
>     --project-name=activiti-cloud-application \
>     --git-api-token=**************************      --git-provider-kind=bitbucketserver     --git-provider-url=https://***-bitbucket.***.com     --git-username=username@***.com

Creating repository ***/activiti-cloud-application
To be able to create a repository on GitHub we need an API Token
Please click this URL and generate a token 
https://github.com/settings/tokens/new?scopes=repo,read:user,read:org,user:email,write:repo_hook,delete_repo

Then COPY the token and enter it below:

? API Token: ****************************************
Generated quickstart at /Users/*****/activiti-cloud-application
### NO charts folder /Users/*****/activiti-cloud-application/charts/activiti-cloud-platform-quickstart
Created project at /Users/*****/activiti-cloud-application
The directory /Users/*****/activiti-cloud-application is not yet using git
? Would you like to initialise git now? Yes
? Commit message:  initial activiti cloud app commit

Git repository created
performing pack detection in folder /Users/*****/activiti-cloud-application
--> Draft detected YAML (76.881356%)
--> Could not find a pack for YAML. Trying to find the next likely language match...
--> Draft detected Shell (19.355932%)
--> Could not find a pack for Shell. Trying to find the next likely language match...
--> Draft detected Coq (3.762712%)
--> Could not find a pack for Coq. Trying to find the next likely language match...
selected pack: /Users/******/.jx/draft/packs/github.com/jenkins-x-buildpacks/jenkins-x-kubernetes/packs/helm
replacing placeholders in directory /Users/*****/activiti-cloud-application
app name: activiti-cloud-application, git server: ***-bitbucket.***.com, org: ****, Docker registry org: ****
skipping directory "/Users/*****/activiti-cloud-application/.git"
Pushed Git repository to https://fng-bitbucket.fox.com/projects/NME/repos/activiti-cloud-application/browse
Created Jenkins Project: http://jenkins.jx.34.83.48.248.nip.io/job/nme/job/activiti-cloud-application/

Watch pipeline activity via:    jx get activity -f activiti-cloud-application -w
Browse the pipeline log via:    jx get build logs nme/activiti-cloud-application/master
You can list the pipelines via: jx get pipelines
When the pipeline is complete:  jx get applications

For more help on available commands see: https://jenkins-x.io/developing/browsing/

Note that your first pipeline may take a few minutes to start while the necessary images get downloaded!

### Expected behavior

activiti-cloud-applicayion gets promoted to namespace staging and pipeline deployed successfully.

### Actual behavior

++ cat ../../VERSION

+ jx promote -b --all-auto --timeout 1h --version 0.0.1

Promoting app activiti-cloud-application version 0.0.1 to namespace staging

Created Pull Request: https://fng-bitbucket.fox.com/projects/NME/repos/environment-activiti7-gke-staging/pull-requests/1

error: Getting content not supported on bitbucket

script returned exit code 1

### Jx version

The output of `jx version` is:

The jx version is 
$ jx version
NAME               VERSION
jx                 2.0.579
jenkins x platform 2.0.930
Kubernetes cluster v1.12.8-gke.10
kubectl            v1.15.2
helm client        v2.14.3+g0e7f3b6
helm server        v2.14.1+g5270352
git                2.22.0
Operating System   Mac OS X 10.14.6 build 18G87

### Jenkins type

Classic Jenkins

### Kubernetes cluster

GKE Kubernetes Cluster

### Operating system / Environment

Mac OS X 10

**Comment by GingerBuffalo** [comment]
I'm also hitting this issue against a gitlab server. Running jenkins x platform 2.0.951.

**Comment by perimori** [comment]
We found out problems started from 2.0.517

After the 'fix: refactor ForkAndPullRepo' commit, promote was not able to get the bitbucket organization / project :
/rest/api/1.0/projects//repos/env-jx-statging/pull-requests</message></status>
404 not found

As of now, we are using 2.0.515 safely with bitbucketserver v5.9.1

**Comment by ehsandanesh** [comment]
I have the same issue with gitlab. I downgraded jx to:
NAME               VERSION
jx                 2.0.515
jenkins x platform 2.0.926
Kubernetes cluster v1.15.2
kubectl            v1.14.3
helm client        Client: v2.14.2+ga8b13cc
git                git version 2.17.1
Operating System   Ubuntu 18.04.3 LTS
but still, no luck! 
Does anyone know what is the best version for jx and jx-platform that does not have any problem with gitlab?
Is there any ETA on when this is going to get resolved or if there is any workaround for it?

**Comment by perimori** [comment]
Hi @ehsandanesh 
You might need to downgrade your platform to v2.0.884 which is using jx 2.0.515 in its dependency matrix.

**Comment by ehsandanesh** [comment]
Now I am getting 
```
jx promote -b --all-auto --timeout 1h --version 0.0.16 --verbose
 DEBUG: Using helmBinary helm with feature flag: template-mode
 Promoting app jx-app-code version 0.0.16 to namespace jx-staging
 DEBUG: Using pipeline: myname/jx-app-code/master build: #5
 DEBUG: merging pipeline secrets with local secrets
 DEBUG: Did not find any PRs to rebase, creating a new one
 Created Pull Request: https://gitlab.team.com/myname/environment-name-jx-staging/merge_requests/3
 DEBUG: Using pipeline: myname/jx-app-code/master build: #5
 WARNING: Failed to query the Pull Request last commit status for https://gitlab.team.com/myname/environment-name-jx-staging/merge_requests/3 ref 6dce90da5e80c17082f223ebf01ccd99eb56f5f7 could not find a status for repository 575 with ref 6dce90da5e80c17082f223ebf01ccd99eb56f5f7
 WARNING: Failed to query the Pull Request last commit status for https://gitlab.team.com/myname/environment-name-jx-staging/merge_requests/3 ref 6dce90da5e80c17082f223ebf01ccd99eb56f5f7 could not find a status for repository 575 with ref 6dce90da5e80c17082f223ebf01ccd99eb56f5f7
 Pull Request https://gitlab.team.com/myname/environment-name-jx-staging/merge_requests/3 is merged at sha fc8484362046fe84dcc36f3a97aa80b82ee7a1f6
 Merge commit has not yet any statuses on repo myname/environment-name-jx-staging merge sha fc8484362046fe84dcc36f3a97aa80b82ee7a1f6
 java.io.EOFException
     at okio.RealBufferedSource.require(RealBufferedSource.java:61)
     at okio.RealBufferedSource.readByte(RealBufferedSource.java:74)
     at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:117)
     at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101)
     at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274)
     at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214)
     at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
     at java.lang.Thread.run(Thread.java:748)
```
and FYI I manually accept merge request which I think should happen automatically and it just stuck there forever!
