### ISSUE TITLE
Periodic jobs not supported in schedulers

### ISSUE THREAD

**Issue by garethjevans** [jenkins-x/jx#5198]
### Summary 

I tried configuring 3 periodic jobs for tekton weasel https://github.com/jenkins-x/environment-tekton-weasel-dev/pull/49, but the validation failed and required me to add an interval and a cron expression.  When the scheduler ran, it the nil errored on buildPeriodics.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x2215f89]

goroutine 1 [running]:
github.com/jenkins-x/jx/pkg/pipelinescheduler.buildPeriodics(0xc000752a80, 0xc0003bdcc0, 0xc000b64928, 0x1)
	/workspace/source/pkg/pipelinescheduler/config_builder.go:606 +0x1c9
github.com/jenkins-x/jx/pkg/pipelinescheduler.buildJobConfig(0xc000752a80, 0xc000752ac0, 0xc000baf2e8, 0xc00067e7e3, 0x9, 0xc00067e800, 0xc, 0x200, 0xc000697800)
	/workspace/source/pkg/pipelinescheduler/config_builder.go:318 +0xd9
github.com/jenkins-x/jx/pkg/pipelinescheduler.BuildProwConfig(0xc000697800, 0x41, 0x80, 0x40, 0x41, 0xc000697800, 0x40)
	/workspace/source/pkg/pipelinescheduler/config_builder.go:25 +0xe4
github.com/jenkins-x/jx/pkg/pipelinescheduler.GenerateProw(0xc000530101, 0x53297c0, 0xc000483040, 0xc00067eb70, 0x2, 0xc000685b00, 0x11, 0xc000217b00, 0x0, 0xc000184310, ...)
	/workspace/source/pkg/pipelinescheduler/generator.go:80 +0x3c5
github.com/jenkins-x/jx/pkg/cmd/step/scheduler.(*StepSchedulerConfigApplyOptions).Run(0xc00081f040, 0x0, 0x0)
	/workspace/source/pkg/cmd/step/scheduler/step_scheduler_config_apply.go:69 +0x2b7
github.com/jenkins-x/jx/pkg/cmd/step/scheduler.NewCmdStepSchedulerConfigApply.func1(0xc0006a8780, 0xc000482c90, 0x0, 0x1)
	/workspace/source/pkg/cmd/step/scheduler/step_scheduler_config_apply.go:47 +0x6f
github.com/spf13/cobra.(*Command).execute(0xc0006a8780, 0xc000482c80, 0x1, 0x1, 0xc0006a8780, 0xc000482c80)
	/workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0xc0004bd180, 0xc0000e3400, 0x5310200, 0xc0000d6000)
	/workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ec
github.com/spf13/cobra.(*Command).Execute(...)
```

**Comment by pmuir** [comment]
After discussion we will ask people to migrate to `CronJob`s in Kubernetes.
