### ISSUE TITLE
SIGSEGV during expose or cleanup

### ISSUE THREAD

**Issue by inish777** [jenkins-x/jx#532]
```
I0330 09:52:46.963137       1 exposecontroller.go:59] Using build: '2.3.56'
I0330 09:52:46.973535       1 config.go:22] No /etc/exposecontroller/config.yml file found.  Will try to figure out defaults
W0330 09:52:46.973560       1 exposecontroller.go:80] %!s(&lt;nil&gt;)
I0330 09:52:46.975254       1 exposecontroller.go:86] Using ConfigMapo exposecontroller to load configuration...
W0330 09:52:46.975299       1 exposecontroller.go:92] Could not parse the config text from exposecontroller ConfigMap  failed to unmarshal config: yaml: line 1: did not find expected alphabetic or numeric character
I0330 09:52:46.975320       1 exposecontroller.go:94] Loaded ConfigMap exposecontroller to load configuration!
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x45cfd8]
 goroutine 1 [running]:
main.main()
	/home/jenkins/go/src/github.com/jenkins-x/exposecontroller/_gopath/src/github.com/jenkins-x/exposecontroller/exposecontroller.go:102 +0x4e2
```
kubernetes v1.9.6

**Comment by jstrachan** [comment]
sorry to hear that. It looks like the ConfigMap called ‘exposecontroller’ could not be parsed.

Any chance you could run this command and attach the output please?

    kubectl get cm exposecontroller -oyaml

**Comment by inish777** [comment]
@jstrachan no problems
```yaml

apiVersion: v1
data:
  config.yml: |-
    exposer: Ingress
    domain: *.jenkins.example.io
    http: true
    tls-acme: false
kind: ConfigMap
metadata:
  creationTimestamp: 2018-04-02T11:15:33Z
  name: exposecontroller
  namespace: jx
  resourceVersion: "1052081"
  selfLink: /api/v1/namespaces/jx/configmaps/exposecontroller
  uid: 29661678-3667-11e8-b4ba-02be5ea48db8

```

**Comment by rawlingsj** [comment]
Sorry for the delay, I'm 99% sure it's because there's an `*` in the domain above.  I'm going to close this as I'm pretty sure `domain: jenkins.example.io` would work.
