### ISSUE TITLE
panic in addBatchBuildData

### ISSUE THREAD

**Issue by abayer** [jenkins-x/jx#5445]
Saw this when a batch started up on prod:
```
{"branch":"batch","component":"pipelinerunner","context":"lint","level":"info","meta":false,"msg":"triggering pipeline","revision":"06f41fddf6b7f4e4ce2413f6ae0f241acf4801bc","sourceURL":"https://github.com/jenkins-x/jx.git","time":"2019-09-11T17:40:01Z"}
{"level":"info","msg":"shallow cloning repository https://github.com/jenkins-x/jx.git to temp dir /tmp/git979880209","time":"2019-09-11T17:40:01Z"}
{"level":"info","msg":"Merged SHA 1895492812b408da4121aae6cc82d8309863bb90 with commit message 'Merge commit 'e21a5d2543f648b2d85aaccbc1a11075de406eed'' into base branch master","time":"2019-09-11T17:40:25Z"}
{"level":"info","msg":"Merged SHA 9d0c49231bc47fcae4a9ef9d3deebf4f6c5c341f with commit message 'Merge commit '7745b4665c01729e07b0fc7bba511dcfe485105a'' into base branch master","time":"2019-09-11T17:40:25Z"}
{"level":"info","msg":"Merged SHA e21a5d2543f648b2d85aaccbc1a11075de406eed with commit message 'feat: avoid passing arguments down the chain with create cluster' into base branch master","time":"2019-09-11T17:40:25Z"}
{"level":"info","msg":"Merged SHA 7745b4665c01729e07b0fc7bba511dcfe485105a with commit message 'fix: allow helm3 to be enabled for boot' into base branch master","time":"2019-09-11T17:40:25Z"}
{"level":"warning","msg":"could not find a stable version for Docker image: busybox in /root/.jx/jenkins-x-versions","time":"2019-09-11T17:40:28Z"}
{"level":"warning","msg":"for background see: https://jenkins-x.io/architecture/version-stream/","time":"2019-09-11T17:40:28Z"}
{"level":"info","msg":"please lock this version down via the command: jx step create version pr -k docker -n busybox -v 1.2.3","time":"2019-09-11T17:40:28Z"}
{"level":"warning","msg":"could not find a stable version for Docker image: busybox in /root/.jx/jenkins-x-versions","time":"2019-09-11T17:40:28Z"}
{"level":"warning","msg":"for background see: https://jenkins-x.io/architecture/version-stream/","time":"2019-09-11T17:40:28Z"}
{"level":"info","msg":"please lock this version down via the command: jx step create version pr -k docker -n busybox -v 1.2.3","time":"2019-09-11T17:40:28Z"}
{"level":"info","msg":"PipelineActivity for jenkins-x-jx-batch-83","time":"2019-09-11T17:40:28Z"}
{"level":"info","msg":"Applying changes ","time":"2019-09-11T17:40:28Z"}
{"level":"info","msg":"removing the temp directory /tmp/git979880209","time":"2019-09-11T17:40:29Z"}
2019/09/11 17:40:30 http: panic serving 10.12.76.228:34656: runtime error: index out of range
goroutine 2209 [running]:
net/http.(*conn).serve.func1(0xc000b7a000)
	/usr/local/go/src/net/http/server.go:1769 +0x139
panic(0x4154080, 0x9f0ec00)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/jenkins-x/jx/pkg/kube.(*PipelineActivityKey).addBatchBuildData(0xc0002a61c0, 0x570a200, 0xc000ac4780, 0xc00060b200, 0x0, 0x0)
	/workspace/source/pkg/kube/activity.go:358 +0xb73
github.com/jenkins-x/jx/pkg/kube.(*PipelineActivityKey).GetOrCreate(0xc0002a61c0, 0x56ab6c0, 0xc0015ac920, 0xc001e0bbcc, 0x2, 0x644d0b, 0x4633c2, 0x2, 0xc000062a00)
	/workspace/source/pkg/kube/activity.go:222 +0x748
github.com/jenkins-x/jx/pkg/tekton.ApplyPipeline(0x56ab6c0, 0xc0015ac920, 0x56ac680, 0xc0015ac520, 0xc000ed5b80, 0xc001e0bbcc, 0x2, 0xc0002a61c0, 0xc0002a61c0, 0x0)
	/workspace/source/pkg/tekton/pipelines.go:341 +0x1536
github.com/jenkins-x/jx/pkg/cmd/step/create.(*StepCreateTaskOptions).Run(0xc0004042c0, 0x0, 0x0)
	/workspace/source/pkg/cmd/step/create/step_create_task.go:371 +0xa8b
github.com/jenkins-x/jx/pkg/cmd/controller/pipeline.(*controller).startPipeline(0xc0005dca20, 0xc000588cf0, 0xc001af603b, 0x5, 0xc001af6800, 0x6, 0xc001af6806, 0x7, 0xc001af680e, 0x2, ...)
	/workspace/source/pkg/cmd/controller/pipeline/pipelinerunner_controller.go:268 +0x8d0
github.com/jenkins-x/jx/pkg/cmd/controller/pipeline.(*controller).handlePostRequest(0xc0005dca20, 0xc0000cef00, 0x56b8300, 0xc0007d8c40)
	/workspace/source/pkg/cmd/controller/pipeline/pipelinerunner_controller.go:185 +0xeb
github.com/jenkins-x/jx/pkg/cmd/controller/pipeline.(*controller).pipeline(0xc0005dca20, 0x56b8300, 0xc0007d8c40, 0xc0000cef00)
	/workspace/source/pkg/cmd/controller/pipeline/pipelinerunner_controller.go:171 +0x1ed
net/http.HandlerFunc.ServeHTTP(0xc00045a000, 0x56b8300, 0xc0007d8c40, 0xc0000cef00)
	/usr/local/go/src/net/http/server.go:1995 +0x44
net/http.(*ServeMux).ServeHTTP(0xc0003cfec0, 0x56b8300, 0xc0007d8c40, 0xc0000cef00)
	/usr/local/go/src/net/http/server.go:2375 +0x1d6
net/http.serverHandler.ServeHTTP(0xc0009220d0, 0x56b8300, 0xc0007d8c40, 0xc0000cef00)
	/usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc000b7a000, 0x56ce000, 0xc001116000)
	/usr/local/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x2f4
```
Looks like the `PipelineActivity` listing filtering for the `lastCommitSha` and `branch` is only finding one activity, causing a panic at an attempt to get the expected rest of the list. I can't tell which commit/branch it's looking for.

**Comment by abayer** [comment]
Check that, it's not finding _any_ activities. I read the lines wrong.

**Comment by abayer** [comment]
Ok, batch is actually working now - I put #5409 on hold, letting #5392 go through on its own, and now removed the hold from #5409, and it's batching properly with #5444. Makes me suspect there was something specifically wrong with the prowjobs for #5392+#5409 - like this:
```
apiVersion: prow.k8s.io/v1
kind: ProwJob
metadata:
  annotations:
    prow.k8s.io/job: lint
  creationTimestamp: "2019-09-11T17:38:29Z"
  generation: 2
  labels:
    created-by-prow: "true"
    prow.k8s.io/job: lint
    prow.k8s.io/refs.org: jenkins-x
    prow.k8s.io/refs.pull: "5392"
    prow.k8s.io/refs.repo: jx
    prow.k8s.io/type: batch
  name: f7ea6015-d4ba-11e9-b2ae-d2488072264d
  namespace: jx
  resourceVersion: "13411796"
  selfLink: /apis/prow.k8s.io/v1/namespaces/jx/prowjobs/f7ea6015-d4ba-11e9-b2ae-d2488072264d
  uid: f7eaf42a-d4ba-11e9-8ad8-42010a8400d7
spec:
  agent: tekton
  cluster: default
  context: lint
  job: lint
  namespace: jx
  refs:
    base_ref: master
    base_sha: 06f41fddf6b7f4e4ce2413f6ae0f241acf4801bc
    org: jenkins-x
    pulls:
    - author: jstrachan
      number: 5392
      sha: 7745b4665c01729e07b0fc7bba511dcfe485105a
    - author: dgozalo
      number: 5409
      sha: e21a5d2543f648b2d85aaccbc1a11075de406eed
    repo: jx
  type: batch
```

`kc get pipelineactivity -l "lastCommitSha in (_sha_), branch in (PR-_number_)"` for both of those pulls worked for me locally, so I have no clue what was going on.

**Comment by abayer** [comment]
@dgozalo, looks like you wrote the original code here?

**Comment by dgozalo** [comment]
Yes, the idea was to enrich the PAs with BatchData, meaning that a batch job would get a reference to which PRs it was comprised of and each of those PRs would get a reference to the batch build.

The last commitSha was to get the latest `PipelineActivity` that was ran for a Pull Request, as that would be the one that was inside a batch build, and update it with the batch build data.

**Comment by abayer** [comment]
I think this may be due to #5552

**Comment by abayer** [comment]
Ok, I'm almost certain it is. https://github.com/jenkins-x/jx/blob/552a55491833902442741d5dc94a3ff0c7b693c5/pkg/kube/activity.go#L468 - since (due to #5552) we're not putting pull refs on `PipelineActivity`s properly when metapipeline is enabled, the activity key isn't being detected as a PR build and the `lastCommitSha` label isn't being put on the label, so that the `lastCommitSha in (_sha_), branch in (PR-_number_)` query isn't finding the original PR builds' activities, resulting in the list only having one item, the batch build itself.

**Comment by abayer** [comment]
I'm leaving this open until I write a test verifying the fix.

**Comment by abayer** [comment]
Ok, https://github.com/jenkins-x/jx/pull/5555 verifies this is fixed, so closing.
