### ISSUE TITLE
jx import with GHE repo results in GO runtime error

### ISSUE THREAD

**Issue by vgallissot** [jenkins-x/jx#564]
I had a go runtime error while using `jx import` in my project and pushing to a GHE repo.

I ran:
```
± jx import
? Which git service do you wish to use https://github.foo.bar
? Do you wish to use bot-jenkins-x as the git user name Yes

...
Writing objects: 100% (16/16), 3.09 KiB | 3.09 MiB/s, done.
Total 16 (delta 1), reused 0 (delta 0)
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To github.foo.bar:my-organization/my-project-to-import.git
   ef84a71..4db77b4  HEAD -> master
WARNING: could not parse URL: git@github.foo.bar:my-organization/my-project-to-import.git due to parse github.foo.bar:my-organization/my-project-to-import.git: first path segment in URL cannot contain colon
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa7b2b0]

goroutine 1 [running]:
github.com/jenkins-x/jx/pkg/gits.(*GitRepositoryInfo).HostURL(0xc42007c550, 0x19491e0, 0xd)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/gits/git_url.go:68 +0x210
github.com/jenkins-x/jx/pkg/jenkins.ImportProject(0x24a7380, 0xc42000c018, 0xc4204dab00, 0xc420316600, 0x3d, 0xc420014004, 0x3b, 0x1945a21, 0xb, 0x1958230, ...)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jenkins/import.go:61 +0x1e1b
github.com/jenkins-x/jx/pkg/jx/cmd.(*ImportOptions).DoImport(0xc4201261c0, 0x0, 0x0)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/import.go:620 +0x257
github.com/jenkins-x/jx/pkg/jx/cmd.(*ImportOptions).Run(0xc4201261c0, 0xc420373c50, 0x0)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/import.go:281 +0x321
github.com/jenkins-x/jx/pkg/jx/cmd.NewCmdImport.func1(0xc4202a9180, 0x2604958, 0x0, 0x0)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/import.go:127 +0x75
github.com/jenkins-x/jx/vendor/github.com/spf13/cobra.(*Command).execute(0xc4202a9180, 0x2604958, 0x0, 0x0, 0xc4202a9180, 0x2604958)
	/home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/jenkins-x/jx/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4200a2f00, 0xc4202f1400, 0xc420049900, 0xc420047680)
	/home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/spf13/cobra/command.go:852 +0x334
github.com/jenkins-x/jx/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4200a2f00, 0xc4203c8a18, 0x24a7300)
	/home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/jenkins-x/jx/cmd/jx/app.Run(0xc4203a7f70, 0x158a989)
	/home/jenkins/go/src/github.com/jenkins-x/jx/cmd/jx/app/jx.go:18 +0x90
main.main()
	/home/jenkins/go/src/github.com/jenkins-x/jx/cmd/jx/jx.go:10 +0x22
```

Of course, I wasn't memoryless,
The 'Draft create' git push to master worked,

```
NAME           VERSION
jx             1.1.44
Jenkins X      0.0.507
```

**Comment by jstrachan** [comment]
ah - I just hit that testing bit bucket - should be fixed in this PR: https://github.com/jenkins-x/jx/pull/565

**Comment by vgallissot** [comment]
OK great, I'll test tomorrow ;)

**Comment by jstrachan** [comment]
the docs still need some polishing - basically you should be able to follow these instructions (when the new release is out) to add a GHE server URL and an API token: 
http://jenkins-x.io/developing/git/

then if you do `jx create cluster ...` or `jx install` it can use GHE for all the git repos for environments + new projects etc

**Comment by vgallissot** [comment]
Totally Approved

jx version: 1.1.48

Before running  `jx install`:
```
$ jx get git
Name   Kind   URL
GitHub GitHub https://github.com
```

```
$ jx create git server github https://github.foo.bar --name='github-foobar'
Added git server github-foobar for URL https://github.foo.bar
```

```
$ jx create git token --name='jenkinsx@github.foo.bar' --url='https://github.foo.bar' jenkinsx --api-token='...'
WARNING: Failed to update jenkins git credentials secret: secrets "jenkins-git-credentials" not found
Created user jenkinsx API Token for git server github-foobar at https://github.foo.bar
```

```
$ jx get git                                                               
Name         Kind   URL
GitHub       GitHub https://github.com
github-foobar github https://github.foo.bar
```

```
$ jx delete git server GitHub                                              
Deleted git servers: GitHub from local settings

$ jx get git
Name         Kind   URL
github-foobar github https://github.foo.bar
```

Then install worked like a charm.
Closing this issue,
Thanks a lot @jstrachan
