### ISSUE TITLE
Batch builds fail to run when builds for one of more of the PRs have all been GCed

### ISSUE THREAD

**Issue by abayer** [jenkins-x/jx#5812]
Seeing this error in `pipelinerunner` logs. Not yet sure why.

```
{"branch":"batch","component":"pipelinerunner","context":"boot-vault","level":"info","meta":true,"msg":"triggering pipeline","revision":"863b456f21d03951ec912bd92339242ab4655bb9","sourceURL":"https://github.com/jenkins-x/jx.git","time":"2019-10-14T18:01:40Z"}
{"level":"info","msg":"PipelineActivity for jenkins-x-jx-PR-5801-12","time":"2019-10-14T18:01:41Z"}
2019/10/14 18:01:42 http: panic serving 10.12.57.243:54376: runtime error: index out of range
goroutine 160942 [running]:
net/http.(*conn).serve.func1(0xc0004b9680)
	/usr/local/go/src/net/http/server.go:1769 +0x139
panic(0x428f2c0, 0xa269bd0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/jenkins-x/jx/pkg/kube.(*PipelineActivityKey).addBatchBuildData(0xc0010dea90, 0x590e560, 0xc000a46740, 0xc000ff4000, 0x0, 0x0)
	/workspace/source/pkg/kube/activity.go:372 +0xb73
github.com/jenkins-x/jx/pkg/kube.(*PipelineActivityKey).GetOrCreate(0xc0010dea90, 0x58ada60, 0xc0007c48a0, 0xc0006c64fc, 0x2, 0x461e07d, 0x0, 0x0, 0x100)
	/workspace/source/pkg/kube/activity.go:226 +0x6ef
github.com/jenkins-x/jx/pkg/tekton.ApplyPipeline(0x58ada60, 0xc0007c48a0, 0x58aea20, 0xc0007c44a0, 0xc0010deb70, 0xc0006c64fc, 0x2, 0xc0010dea90, 0x0, 0x170000c0010decd0)
	/workspace/source/pkg/tekton/pipelines.go:340 +0x1536
github.com/jenkins-x/jx/pkg/tekton/metapipeline.(*clientFactory).Apply(0xc00053e2a0, 0xc000bc67a0, 0x17, 0xc000bc67c0, 0x14, 0x4cac6e7, 0x2, 0x0, 0x0, 0x0, ...)
	/workspace/source/pkg/tekton/metapipeline/clientfactory.go:160 +0x8d
github.com/jenkins-x/jx/pkg/cmd/controller/pipeline.(*controller).triggerMetaPipeline(0xc0009fa000, 0xc000992e70, 0xc000be24eb, 0x5, 0xc000be24f0, 0x6, 0xc000be24f6, 0x7, 0xc000be24fe, 0x2, ...)
	/workspace/source/pkg/cmd/controller/pipeline/pipelinerunner_controller.go:339 +0x6c4
github.com/jenkins-x/jx/pkg/cmd/controller/pipeline.(*controller).startPipeline(0xc0009fa000, 0xc000992e70, 0xc000be24eb, 0x5, 0xc000be24f0, 0x6, 0xc000be24f6, 0x7, 0xc000be24fe, 0x2, ...)
	/workspace/source/pkg/cmd/controller/pipeline/pipelinerunner_controller.go:260 +0x72c
github.com/jenkins-x/jx/pkg/cmd/controller/pipeline.(*controller).handlePostRequest(0xc0009fa000, 0xc000915f00, 0x58ba6a0, 0xc0010741c0)
	/workspace/source/pkg/cmd/controller/pipeline/pipelinerunner_controller.go:185 +0xeb
github.com/jenkins-x/jx/pkg/cmd/controller/pipeline.(*controller).pipeline(0xc0009fa000, 0x58ba6a0, 0xc0010741c0, 0xc000915f00)
	/workspace/source/pkg/cmd/controller/pipeline/pipelinerunner_controller.go:171 +0x1ed
net/http.HandlerFunc.ServeHTTP(0xc0009cd400, 0x58ba6a0, 0xc0010741c0, 0xc000915f00)
	/usr/local/go/src/net/http/server.go:1995 +0x44
net/http.(*ServeMux).ServeHTTP(0xc0006b6900, 0x58ba6a0, 0xc0010741c0, 0xc000915f00)
	/usr/local/go/src/net/http/server.go:2375 +0x1d6
net/http.serverHandler.ServeHTTP(0xc0009ad520, 0x58ba6a0, 0xc0010741c0, 0xc000915f00)
	/usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc0004b9680, 0x58d10e0, 0xc00132b480)
	/usr/local/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x2f4
```

**Comment by abayer** [comment]
So it knows it's a batch build, but can't find any `PipelineActivity`s with the relevant `lastCommitSha` and `branch` for at least one of the PRs in the batch.

**Comment by abayer** [comment]
aaaaaaah - one of the PRs has gone long enough since its last build that there is no `PipelineActivity` for its builds any more. They've been GCed. So...yeah. We need to be cleaner about handling that.
