### ISSUE TITLE
aks cluster - environment-xxxxxx-staging and production builds - "Still waiting to schedule task "Waiting for next available executor"

### ISSUE THREAD

**Issue by petervdm** [jenkins-x/jx#603]
Hi, I installed a cluster on aks using:
`jx create cluster aks`

All went smoothly, but the initial staging and production builds are stuck at this.

ERROR: Failed to delete pod for agent jx/maven-7x8dk: Operation: [delete]  for kind: [Pod]  with name: [maven-7x8dk]  in namespace: [jx]  failed.
Apr 09, 2018 7:04:14 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave _terminate
WARNING: Failed to delete pod for agent jx/maven-7x8dk: Operation: [delete]  for kind: [Pod]  with name: [maven-7x8dk]  in namespace: [jx]  failed.
io.fabric8.kubernetes.client.KubernetesClientException: Operation: [delete]  for kind: [Pod]  with name: [maven-7x8dk]  in namespace: [jx]  failed.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:62)
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:71)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.deleteThis(BaseOperation.java:687)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.delete(BaseOperation.java:626)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.delete(BaseOperation.java:70)
	at org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave._terminate(KubernetesSlave.java:212)
	at hudson.slaves.AbstractCloudSlave.terminate(AbstractCloudSlave.java:67)
	at org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher.launch(KubernetesLauncher.java:197)
	at hudson.slaves.SlaveComputer$1.call(SlaveComputer.java:288)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.net.ssl.SSLPeerUnverifiedException: Hostname kubernetes.default not verified:
    certificate: sha256/pAVdpHwWYxCi06OtZiG6j5Srvcma7GmszAOQMX58cYU=
    DN: CN=apiserver
    subjectAltNames: [10.0.0.1, 10.0.0.1, hcp-kubernetes, kubernetes, kubernetes.default.svc, kubernetes.default.svc.cluster.local, hcp-kubernetes.5acb8e814ce33c00018213b7.svc.cluster.local, nosefield--nosefield-8fef1a-914ff0dd.hcp.eastus.azmk8s.io]
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:290)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:251)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:151)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:195)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at io.fabric8.kubernetes.client.utils.HttpClientUtils$2.intercept(HttpClientUtils.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
	at okhttp3.RealCall.execute(RealCall.java:69)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:377)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:343)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleDelete(OperationSupport.java:208)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.deleteThis(BaseOperation.java:684)
	... 11 more

Apr 09, 2018 7:04:24 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud provision
INFO: Excess workload after pending Kubernetes agents: 2
Apr 09, 2018 7:04:24 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud provision
INFO: Template: Kubernetes Pod Template
Apr 09, 2018 7:04:24 PM hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
INFO: Started provisioning Kubernetes Pod Template from kubernetes with 1 executors. Remaining excess workload: 0.98
Apr 09, 2018 7:04:24 PM hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
INFO: Started provisioning Kubernetes Pod Template from kubernetes with 1 executors. Remaining excess workload: -0.02
Apr 09, 2018 7:04:34 PM hudson.slaves.NodeProvisioner$2 run
INFO: Kubernetes Pod Template provisioning successfully completed. We have now 2 computer(s)
Apr 09, 2018 7:04:34 PM hudson.slaves.NodeProvisioner$2 run
INFO: Kubernetes Pod Template provisioning successfully completed. We have now 3 computer(s)
Apr 09, 2018 7:04:34 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud provision
INFO: Excess workload after pending Kubernetes agents: 0
Apr 09, 2018 7:04:34 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud provision
INFO: Template: Kubernetes Pod Template
Apr 09, 2018 7:04:34 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher launch
WARNING: Error in provisioning; agent=KubernetesSlave name: maven-st901, template=PodTemplate{inheritFrom='', name='maven', slaveConnectTimeout=0, label='jenkins-maven', serviceAccount='jenkins', nodeSelector='', volumes=[org.csanchez.jenkins.plugins.kubernetes.volumes.SecretVolume@50606cff, org.csanchez.jenkins.plugins.kubernetes.volumes.SecretVolume@664c5680, org.csanchez.jenkins.plugins.kubernetes.volumes.SecretVolume@7653f2d, org.csanchez.jenkins.plugins.kubernetes.volumes.SecretVolume@437b2cba, org.csanchez.jenkins.plugins.kubernetes.volumes.HostPathVolume@102fa7be], containers=[ContainerTemplate{name='jnlp', image='jenkinsci/jnlp-slave:3.14-1', workingDir='/home/jenkins', command='', args='${computer.jnlpmac} ${computer.name}', resourceRequestCpu='100m', resourceRequestMemory='128Mi', resourceLimitCpu='', resourceLimitMemory=''}, ContainerTemplate{name='maven', image='jenkinsxio/builder-maven:0.0.141', privileged=true, workingDir='/home/jenkins', command='/bin/sh -c', args='cat', ttyEnabled=true, resourceRequestCpu='400m', resourceRequestMemory='512Mi', resourceLimitCpu='1', resourceLimitMemory='1024Mi'}], envVars=[ContainerEnvVar [getValue()=/home/jenkins/.docker/, getKey()=DOCKER_CONFIG], ContainerEnvVar [getValue()=jenkins-x@googlegroups.com, getKey()=GIT_AUTHOR_EMAIL], ContainerEnvVar [getValue()=jenkins-x-bot, getKey()=GIT_AUTHOR_NAME], ContainerEnvVar [getValue()=jenkins-x@googlegroups.com, getKey()=GIT_COMMITTER_EMAIL], ContainerEnvVar [getValue()=jenkins-x-bot, getKey()=GIT_COMMITTER_NAME], ContainerEnvVar [getValue()=http://jenkins:8080, getKey()=JENKINS_URL], ContainerEnvVar [getValue()=/home/jenkins, getKey()=XDG_CONFIG_HOME], ContainerEnvVar [getValue()=-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Xms10m -Xmx192m, getKey()=_JAVA_OPTIONS]]}
io.fabric8.kubernetes.client.KubernetesClientException: Operation: [create]  for kind: [Pod]  with name: [null]  in namespace: [jx]  failed.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:62)
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:71)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:363)
	at org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher.launch(KubernetesLauncher.java:105)
	at hudson.slaves.SlaveComputer$1.call(SlaveComputer.java:288)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.net.ssl.SSLPeerUnverifiedException: Hostname kubernetes.default not verified:
    certificate: sha256/pAVdpHwWYxCi06OtZiG6j5Srvcma7GmszAOQMX58cYU=
    DN: CN=apiserver
    subjectAltNames: [10.0.0.1, 10.0.0.1, hcp-kubernetes, kubernetes, kubernetes.default.svc, kubernetes.default.svc.cluster.local, hcp-kubernetes.5acb8e814ce33c00018213b7.svc.cluster.local, nosefield--nosefield-8fef1a-914ff0dd.hcp.eastus.azmk8s.io]
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:290)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:251)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:151)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:195)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at io.fabric8.kubernetes.client.utils.HttpClientUtils$2.intercept(HttpClientUtils.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
	at okhttp3.RealCall.execute(RealCall.java:69)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:377)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:343)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:226)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:769)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:356)
	... 7 more

Apr 09, 2018 7:04:34 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave _terminate
INFO: Terminating Kubernetes instance for agent maven-st901
Apr 09, 2018 7:04:34 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher launch
WARNING: Error in provisioning; agent=KubernetesSlave name: maven-c7gm9, template=PodTemplate{inheritFrom='', name='maven', slaveConnectTimeout=0, label='jenkins-maven', serviceAccount='jenkins', nodeSelector='', volumes=[org.csanchez.jenkins.plugins.kubernetes.volumes.SecretVolume@50606cff, org.csanchez.jenkins.plugins.kubernetes.volumes.SecretVolume@664c5680, org.csanchez.jenkins.plugins.kubernetes.volumes.SecretVolume@7653f2d, org.csanchez.jenkins.plugins.kubernetes.volumes.SecretVolume@437b2cba, org.csanchez.jenkins.plugins.kubernetes.volumes.HostPathVolume@102fa7be], containers=[ContainerTemplate{name='jnlp', image='jenkinsci/jnlp-slave:3.14-1', workingDir='/home/jenkins', command='', args='${computer.jnlpmac} ${computer.name}', resourceRequestCpu='100m', resourceRequestMemory='128Mi', resourceLimitCpu='', resourceLimitMemory=''}, ContainerTemplate{name='maven', image='jenkinsxio/builder-maven:0.0.141', privileged=true, workingDir='/home/jenkins', command='/bin/sh -c', args='cat', ttyEnabled=true, resourceRequestCpu='400m', resourceRequestMemory='512Mi', resourceLimitCpu='1', resourceLimitMemory='1024Mi'}], envVars=[ContainerEnvVar [getValue()=/home/jenkins/.docker/, getKey()=DOCKER_CONFIG], ContainerEnvVar [getValue()=jenkins-x@googlegroups.com, getKey()=GIT_AUTHOR_EMAIL], ContainerEnvVar [getValue()=jenkins-x-bot, getKey()=GIT_AUTHOR_NAME], ContainerEnvVar [getValue()=jenkins-x@googlegroups.com, getKey()=GIT_COMMITTER_EMAIL], ContainerEnvVar [getValue()=jenkins-x-bot, getKey()=GIT_COMMITTER_NAME], ContainerEnvVar [getValue()=http://jenkins:8080, getKey()=JENKINS_URL], ContainerEnvVar [getValue()=/home/jenkins, getKey()=XDG_CONFIG_HOME], ContainerEnvVar [getValue()=-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Xms10m -Xmx192m, getKey()=_JAVA_OPTIONS]]}
io.fabric8.kubernetes.client.KubernetesClientException: Operation: [create]  for kind: [Pod]  with name: [null]  in namespace: [jx]  failed.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:62)
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:71)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:363)
	at org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher.launch(KubernetesLauncher.java:105)
	at hudson.slaves.SlaveComputer$1.call(SlaveComputer.java:288)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.net.ssl.SSLPeerUnverifiedException: Hostname kubernetes.default not verified:
    certificate: sha256/pAVdpHwWYxCi06OtZiG6j5Srvcma7GmszAOQMX58cYU=
    DN: CN=apiserver
    subjectAltNames: [10.0.0.1, 10.0.0.1, hcp-kubernetes, kubernetes, kubernetes.default.svc, kubernetes.default.svc.cluster.local, hcp-kubernetes.5acb8e814ce33c00018213b7.svc.cluster.local, nosefield--nosefield-8fef1a-914ff0dd.hcp.eastus.azmk8s.io]
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:290)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:251)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:151)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:195)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at io.fabric8.kubernetes.client.utils.HttpClientUtils$2.intercept(HttpClientUtils.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
	at okhttp3.RealCall.execute(RealCall.java:69)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:377)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:343)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:226)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:769)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:356)
	... 7 more

Apr 09, 2018 7:04:34 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave _terminate
INFO: Terminating Kubernetes instance for agent maven-c7gm9

**Comment by rawlingsj** [comment]
It looks like the certs that have been created by AKS aren't including the `kubernetes.default` hostname from the error above:
```
Caused by: javax.net.ssl.SSLPeerUnverifiedException: Hostname kubernetes.default not verified:
certificate: sha256/pAVdpHwWYxCi06OtZiG6j5Srvcma7GmszAOQMX58cYU=
DN: CN=apiserver
subjectAltNames: [10.0.0.1, 10.0.0.1, hcp-kubernetes, kubernetes, kubernetes.default.svc, kubernetes.default.svc.cluster.local, hcp-kubernetes.5acb8e814ce33c00018213b7.svc.cluster.local, nosefield--nosefield-8fef1a-914ff0dd.hcp.eastus.azmk8s.io
```
I wonder if you can go to the main jenkins system config UI and change the kubernetes plugin server URL from `https://kubernetes.default` to `https://kubernetes.default.svc` and try another build?

If that works maybe we should always include the hostname path https://github.com/jenkins-x/charts/blob/jenkins/stable/jenkins/templates/config.yaml#L100:41

**Comment by petervdm** [comment]
Thank you!  That did the job.

**Comment by liuxiaopiao** [comment]
@rawlingsj , does jenkins x have plan to fix this by updating https://github.com/jenkins-x/charts/blob/jenkins/stable/jenkins/templates/config.yaml#L100:41?
