### ISSUE TITLE
Jenkins environment build failing with failed to access team settings: failed to create the jx client

### ISSUE THREAD

**Issue by cnorburn** [jenkins-x/jx#6077]
### Summary 

it is in fact the API server that it's timing out on

environment build is failing with 
`error: failed to access team settings: failed to create the jx client: Get https://azure-link-to-api-server:443/api/v1/namespaces/jenkins-x: dial tcp 51.140.221.95:443: i/o timeout`
in the Jenkins console log

clicking on the above link gives:
```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}
```
```
+ jx step helm build
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
WARNING: Failed to retrieve team settings: failed to create the jx client: Get https://azure-link-to-api-server:443/api/v1/namespaces/jenkins-x: dial tcp 51.140.221.95:443: i/o timeout - falling back to default settings...
error: failed to access team settings: failed to create the jx client: Get https://azure-link-to-api-server:443/api/v1/namespaces/jenkins-x: dial tcp 51.140.221.95:443: i/o timeout
```
Update:
The above is working now, but i'm getting a similar error in another environment:
```
Applying Apps chart overrides
Applying chart overrides
error: upgrading helm chart '.': failed to run 'helm upgrade --namespace uat --install --wait --force --timeout 600 --values /tmp/values.yaml574954491 uat .' command in directory '/tmp/jx-helm-apply-471273187/env', 
output: 'Error: Get https://azure-link-to-resource-group:443/api/v1/namespaces/kube-system/pods?labelSelector=app%3Dhelm%2Cname%3Dtiller: dial tcp 51.140.221.95:443: i/o timeout'
```

jx or azure problem?

### Steps to reproduce the behavior

Start the environment build

### Expected behavior

A successful build

### Actual behavior

The above failure
It's a mature production cluster on Azure, i've never seen this error before

### Jx version

The output of `jx version` is:

```
jx                 2.0.974
jenkins x platform 2.0.1287
Kubernetes cluster v1.13.10
kubectl            v1.15.3
helm client        v2.14.0+g05811b8
helm server        v2.14.3+g0e7f3b6
git                2.23.0
Operating System   Mac OS X 10.14.6 build 18G95
```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [x ] Classic Jenkins

### Kubernetes cluster

Azure, `jx create cluster`

### Operating system / Environment

osx

**Comment by cnorburn** [comment]
i've upgraded the jx platform and kubernetes:

```
jx                 2.0.974
jenkins x platform 2.0.1607
Kubernetes cluster v1.14.8
kubectl            v1.15.3
helm client        v2.14.0+g05811b8
helm server        v2.14.3+g0e7f3b6
git                2.23.0
Operating System   Mac OS X 10.14.6 build 18G95
```
I'm still facing this error in my environment builds:

```
[Pipeline] {
[Pipeline] sh
+ jx step helm build
WARNING: failed to get the team settings: failed to create the jx client: Get https://azure-link-to-resource-group:443/api/v1/namespaces/jenkins-x: dial tcp 51.140.221.95:443: i/o timeout
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
WARNING: Failed to retrieve team settings: failed to create the jx client: Get https://azure-link-to-resource-group:443/api/v1/namespaces/jenkins-x: dial tcp 51.140.221.95:443: i/o timeout - falling back to default settings...
error: failed to access team settings: failed to create the jx client: Get https://azure-link-to-resource-group:443/api/v1/namespaces/jenkins-x: dial tcp 51.140.221.95:443: i/o timeout
```

Any thoughts on this?

**Comment by cnorburn** [comment]
More information:

The cluster is stable but every build is now failing in Jenkins
It's now at the stage we're going to have to drop jx and use Azure DevOps.
Anybody have any ideas looking at the Jenkins logs below?

We've raised a case with Microsoft, they're going to blame jx :)

We suspect it's an issue with the API Server timing out.

Thanks


```
SEVERE: Timer task org.jenkinsci.plugins.jx.resources.BuildSyncRunListener$1@26d3917c failed
io.fabric8.kubernetes.client.KubernetesClientException: Operation: [get]  for kind: [PipelineActivity]  with name: [careers-ccdg-cw-kube-env-sysint-master-304]  in namespace: [jenkins-x]  failed.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:62)
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:71)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:207)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:163)
	at org.jenkinsci.plugins.jx.resources.BuildSyncRunListener.upsertBuild(BuildSyncRunListener.java:247)
	at org.jenkinsci.plugins.jx.resources.BuildSyncRunListener.pollRun(BuildSyncRunListener.java:186)
	at org.jenkinsci.plugins.jx.resources.BuildSyncRunListener.pollLoop(BuildSyncRunListener.java:174)
	at org.jenkinsci.plugins.jx.resources.BuildSyncRunListener$1.doRun(BuildSyncRunListener.java:138)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:72)
	at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:58)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketTimeoutException: timeout
	at okio.Okio$4.newTimeoutException(Okio.java:230)
	at okio.AsyncTimeout.exit(AsyncTimeout.java:285)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:241)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:345)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:217)
	at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:212)
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at io.fabric8.kubernetes.client.utils.ImpersonatorInterceptor.intercept(ImpersonatorInterceptor.java:56)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at io.fabric8.kubernetes.client.utils.HttpClientUtils$2.intercept(HttpClientUtils.java:107)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall.execute(RealCall.java:77)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:379)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:344)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:313)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:296)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:780)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:196)
	... 14 more
Caused by: java.net.SocketException: Socket closed
	at java.net.SocketInputStream.read(SocketInputStream.java:204)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:933)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at okio.Okio$2.read(Okio.java:139)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
	... 45 more

Dec 06, 2019 10:02:43 AM okhttp3.internal.platform.Platform log
INFO: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
Dec 06, 2019 10:02:55 AM hudson.triggers.SafeTimerTask run
SEVERE: Timer task org.jenkinsci.plugins.jx.resources.BuildSyncRunListener$1@26d3917c failed
io.fabric8.kubernetes.client.KubernetesClientException: Operation: [list]  for kind: [CustomResourceDefinition]  with name: [null]  in namespace: [null]  failed.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:62)
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:71)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:588)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:49)
	at io.jenkins.x.client.kube.ClientHelper.pipelineActivityClient(ClientHelper.java:21)
	at org.jenkinsci.plugins.jx.resources.BuildSyncRunListener.upsertBuild(BuildSyncRunListener.java:217)
	at org.jenkinsci.plugins.jx.resources.BuildSyncRunListener.pollRun(BuildSyncRunListener.java:186)
	at org.jenkinsci.plugins.jx.resources.BuildSyncRunListener.pollLoop(BuildSyncRunListener.java:174)
	at org.jenkinsci.plugins.jx.resources.BuildSyncRunListener$1.doRun(BuildSyncRunListener.java:138)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:72)
	at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:58)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketTimeoutException: timeout
	at okio.Okio$4.newTimeoutException(Okio.java:230)
	at okio.AsyncTimeout.exit(AsyncTimeout.java:285)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:241)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:345)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:217)
	at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:212)
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at io.fabric8.kubernetes.client.utils.ImpersonatorInterceptor.intercept(ImpersonatorInterceptor.java:56)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at io.fabric8.kubernetes.client.utils.HttpClientUtils$2.intercept(HttpClientUtils.java:107)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall.execute(RealCall.java:77)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:379)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:344)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:328)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:584)
	... 15 more
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:933)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at okio.Okio$2.read(Okio.java:139)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
	... 44 more
```

**Comment by Dohbedoh** [comment]
This looks like a read timeout issue from the kubernetes client. The default is 10s IIRC and can be adjusted with a system property [-Dkubernetes.request.timeout=<timeInMillis>](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java#L86)
