### ISSUE TITLE
JX Import failed on previously imported project

### ISSUE THREAD

**Issue by salaboy** [jenkins-x/jx#6203]
### Summary 

After doing `jx import` once into a project, then delete and then re import (deleting all JX files) the CLI fails with: 
```
Creating GitHub webhook for salaboy/demo-conference-monolith for url http://hook-jx.35.205.241.218.nip.io/hook
WARNING: No changes made to the source code in /var/folders/lb/8zfc2j616nq0831p_qm_7zv00000gn/T/create-pr897721288. Code must be up to date!
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x303925b]

goroutine 1 [running]:
github.com/jenkins-x/jx/pkg/gits/operations.(*PullRequestOperation).CreatePullRequest(0xc000f63260, 0x58343a9, 0x8, 0xc000b2a4e0, 0x1, 0xc000218c80, 0x37)
	/workspace/source/pkg/gits/operations/pull_request_op.go:97 +0x51b
github.com/jenkins-x/jx/pkg/cmd/step/create/pr.(*StepCreatePrOptions).CreatePullRequest(0xc000f63588, 0x58343a9, 0x8, 0xc000b2a4e0, 0x0, 0x1)
	/workspace/source/pkg/cmd/step/create/pr/step_create_pr.go:128 +0xa8
github.com/jenkins-x/jx/pkg/cmd/importcmd.(*ImportOptions).addProwConfig(0xc0008aa280, 0xc000972b80, 0x37, 0x582f307, 0x6, 0x0, 0x0)
	/workspace/source/pkg/cmd/importcmd/import.go:1041 +0xa46
github.com/jenkins-x/jx/pkg/cmd/importcmd.(*ImportOptions).doImport(0xc0008aa280, 0xc000994e00, 0x0)
	/workspace/source/pkg/cmd/importcmd/import.go:960 +0x1e1
github.com/jenkins-x/jx/pkg/cmd/importcmd.(*ImportOptions).Run(0xc0008aa280, 0x0, 0x0)
	/workspace/source/pkg/cmd/importcmd/import.go:449 +0x939
github.com/jenkins-x/jx/pkg/cmd/importcmd.NewCmdImport.func1(0xc0008aa500, 0xb0b5690, 0x0, 0x0)
	/workspace/source/pkg/cmd/importcmd/import.go:150 +0x6f
github.com/spf13/cobra.(*Command).execute(0xc0008aa500, 0xb0b5690, 0x0, 0x0, 0xc0008aa500, 0xb0b5690)
	/workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002eb400, 0xc000ad47c0, 0x655e0a0, 0xc0000cc000)
	/workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
	/workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/jenkins-x/jx/cmd/jx/app.Run(0x0, 0x0, 0x0, 0xc000a8bf88, 0xc0000b8058)
	/workspace/source/cmd/jx/app/jx.go:19 +0x17e
main.main()
	/workspace/source/cmd/jx/jx.go:11 +0x32
``` 

### Steps to reproduce the behavior
- Create a spring boot project
- import it 
- delete it with jx delete application 
- delete all JX related files
-  jx import again. 

### Actual behavior
Fails 

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1011
Kubernetes cluster v1.13.11-gke.14
kubectl            v1.16.2
helm client        Client: v2.14.3+g0e7f3b6
git                2.21.0 (Apple Git-122)
Operating System   Mac OS X 10.15.1 build 19B88
```

### Jenkins type

- [ x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by abayer** [comment]
So the underlying problem here is that we now add the imported repo to the dev env’s list of source repositories, but we don’t remove it if the project is deleted. #6210 should address the immediate symptoms, by just skipping the failing attempt to create a PR if the source repo is already present, but we also should really have deletion truly delete.
