### ISSUE TITLE
controller build hangs

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#6246]
just seen a controllerbuild hang and stop updating `PipelineActivity` records when using lighthouse...

```

goroutine 0 [idle]:
runtime.epollwait(0x4, 0x7ffdcf62cdf0, 0xffffffff00000080, 0x0, 0xffffffff03f4e06b, 0x22500000000, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/runtime/sys_linux_amd64.s:675 +0x20
runtime.netpoll(0xc000060501, 0x1)
	/usr/local/go/src/runtime/netpoll_epoll.go:71 +0x126
runtime.findrunnable(0xc00005e000, 0x0)
	/usr/local/go/src/runtime/proc.go:2380 +0x51f
runtime.schedule()
	/usr/local/go/src/runtime/proc.go:2525 +0x21c
runtime.goexit0(0xc000d2af00)
	/usr/local/go/src/runtime/proc.go:2722 +0x1dd
runtime.mcall(0x0)
	/usr/local/go/src/runtime/asm_amd64.s:299 +0x5b

goroutine 1 [select (no cases), 123 minutes]:
github.com/jenkins-x/jx/pkg/cmd/controller.(*ControllerBuildOptions).Run(0xc000358690, 0x0, 0x0)
	/workspace/source/pkg/cmd/controller/controller_build.go:248 +0x11fb
github.com/jenkins-x/jx/pkg/cmd/controller.NewCmdControllerBuild.func1(0xc000648000, 0xc0008ed940, 0x0, 0x4)
	/workspace/source/pkg/cmd/controller/controller_build.go:118 +0x6f
github.com/spf13/cobra.(*Command).execute(0xc000648000, 0xc0008ed900, 0x4, 0x4, 0xc000648000, 0xc0008ed900)
	/workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0xc000673400, 0xc0007a4e40, 0x5905f20, 0xc00000e010)
	/workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
	/workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/jenkins-x/jx/cmd/jx/app.Run(0x0, 0x0, 0x0, 0xc0008e3f88, 0xc00009c058)
	/workspace/source/cmd/jx/app/jx.go:19 +0x185
main.main()
	/workspace/source/cmd/jx/jx.go:11 +0x32

goroutine 5 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0xa333720)
	/workspace/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:882 +0x8b
created by github.com/golang/glog.init.0
	/workspace/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:410 +0x272

goroutine 11 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc000260800)
	/workspace/go/pkg/mod/go.opencensus.io@v0.18.0/stats/view/worker.go:152 +0xdd
created by go.opencensus.io/stats/view.init.0
	/workspace/go/pkg/mod/go.opencensus.io@v0.18.0/stats/view/worker.go:29 +0x57

goroutine 12 [syscall, 123 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 24 [IO wait, 9 minutes]:
internal/poll.runtime_pollWait(0x7f28e34f5f08, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc000c6d718, 0x72, 0xd800, 0xd886, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000c6d700, 0xc001096000, 0xd886, 0xd886, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc000c6d700, 0xc001096000, 0xd886, 0xd886, 0x203000, 0x7f28e34c8b90, 0x5)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc00000e008, 0xc001096000, 0xd886, 0xd886, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:177 +0x69
crypto/tls.(*atLeastReader).Read(0xc000cb40a0, 0xc001096000, 0xd886, 0xd886, 0x28c1948dbaad5b8e, 0xc000b95a30, 0xc000b959e0)
	/usr/local/go/src/crypto/tls/conn.go:761 +0x60
bytes.(*Buffer).ReadFrom(0xc000798cd8, 0x58cfb20, 0xc000cb40a0, 0x409c85, 0x4332ee0, 0x4807700)
	/usr/local/go/src/bytes/buffer.go:207 +0xbd
crypto/tls.(*Conn).readFromUntil(0xc000798a80, 0x58d9a80, 0xc00000e008, 0x5, 0xc00000e008, 0xc000e9c030)
	/usr/local/go/src/crypto/tls/conn.go:783 +0xf8
crypto/tls.(*Conn).readRecordOrCCS(0xc000798a80, 0x4d6c200, 0xc000798bb8, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:590 +0x125
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:558
crypto/tls.(*Conn).Read(0xc000798a80, 0xc0002da000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1236 +0x137
bufio.(*Reader).Read(0xc00009ad20, 0xc00014c3b8, 0x9, 0x9, 0x40566c, 0xc00011d980, 0x4)
	/usr/local/go/src/bufio/bufio.go:223 +0x23e
io.ReadAtLeast(0x58cf880, 0xc00009ad20, 0xc00014c3b8, 0x9, 0x9, 0x9, 0xc00080c0d8, 0xc000be4118, 0x8)
	/usr/local/go/src/io/io.go:310 +0x88
io.ReadFull(...)
	/usr/local/go/src/io/io.go:329
golang.org/x/net/http2.readFrameHeader(0xc00014c3b8, 0x9, 0x9, 0x58cf880, 0xc00009ad20, 0x0, 0x0, 0xc000b95e28, 0x93aae9)
	/workspace/go/pkg/mod/golang.org/x/net@v0.0.0-20190613194153-d28f0bde5980/http2/frame.go:237 +0x88
golang.org/x/net/http2.(*Framer).ReadFrame(0xc00014c380, 0xc0011bc0c0, 0x0, 0x0, 0x0)
	/workspace/go/pkg/mod/golang.org/x/net@v0.0.0-20190613194153-d28f0bde5980/http2/frame.go:492 +0xa1
golang.org/x/net/http2.(*clientConnReadLoop).run(0xc000b95fb8, 0x4d6a6f0, 0xc00091a7b8)
	/workspace/go/pkg/mod/golang.org/x/net@v0.0.0-20190613194153-d28f0bde5980/http2/transport.go:1686 +0x8d
golang.org/x/net/http2.(*ClientConn).readLoop(0xc00011de00)
	/workspace/go/pkg/mod/golang.org/x/net@v0.0.0-20190613194153-d28f0bde5980/http2/transport.go:1614 +0x76
created by golang.org/x/net/http2.(*Transport).newClientConn
	/workspace/go/pkg/mod/golang.org/x/net@v0.0.0-20190613194153-d28f0bde5980/http2/transport.go:673 +0x637

goroutine 33 [sync.Cond.Wait, 3 minutes]:
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:307
sync.runtime_notifyListWait(0xc00081e0d8, 0xc00000000d)
	/usr/local/go/src/runtime/sema.go:510 +0xf9
sync.(*Cond).Wait(0xc00081e0c8)
	/usr/local/go/src/sync/cond.go:56 +0x9e
k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc00081e0b0, 0xc001086ba0, 0x0, 0x0, 0x0, 0x0)
	/workspace/go/pkg/mod/k8s.io/client-go@v2.0.0-alpha.0.0.20190115164855-701b91367003+incompatible/tools/cache/delta_fifo.go:431 +0x8e
k8s.io/client-go/tools/cache.(*controller).processLoop(0xc00043d700)
	/workspace/go/pkg/mod/k8s.io/client-go@v2.0.0-alpha.0.0.20190115164855-701b91367003+incompatible/tools/cache/controller.go:150 +0x40
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000b96fb0)
	/workspace/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190122181752-bebe27e40fb7/pkg/util/wait/wait.go:133 +0x54
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000b96fb0, 0x3b9aca00, 0x0, 0xc000350501, 0xc0004e0000)
	/workspace/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190122181752-bebe27e40fb7/pkg/util/wait/wait.go:134 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/workspace/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190122181752-bebe27e40fb7/pkg/util/wait/wait.go:88
k8s.io/client-go/tools/cache.(*controller).Run(0xc00043d700, 0xc0004e0000)
	/workspace/go/pkg/mod/k8s.io/client-go@v2.0.0-alpha.0.0.20190115164855-701b91367003+incompatible/tools/cache/controller.go:124 +0x2a8
created by github.com/jenkins-x/jx/pkg/kube.CreateEnvironmentCache
	/workspace/source/pkg/kube/env_cache.go:46 +0x3fa

goroutine 28 [chan receive, 123 minutes]:
k8s.io/client-go/tools/cache.(*controller).Run.func1(0xc0004e0000, 0xc00043d700)
	/workspace/go/pkg/mod/k8s.io/client-go@v2.0.0-alpha.0.0.20190115164855-701b91367003+incompatible/tools/cache/controller.go:103 +0x34
created by k8s.io/client-go/tools/cache.(*controller).Run
	/workspace/go/pkg/mod/k8s.io/client-go@v2.0.0-alpha.0.0.20190115164855-701b91367003+incompatible/tools/cache/controller.go:102 +0x92

goroutine 29 [select, 9 minutes]:
k8s.io/client-go/tools/cache.(*Reflector).watchHandler(0xc0007adb80, 0x59040e0, 0xc0011bc540, 0xc000bd5bb0, 0xc000890180, 0xc0004e0000, 0x0, 0x0)
	/workspace/go/pkg/mod/k8s.io/client-go@v2.0.0-alpha.0.0.20190115164855-701b91367003+incompatible/tools/cache/reflector.go:302 +0x23c
k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch(0xc0007adb80, 0xc0004e0000, 0x0, 0x0)
	/workspace/go/pkg/mod/k8s.io/client-go@v2.0.0-alpha.0.0.20190115164855-701b91367003+incompatible/tools/cache/reflector.go:268 +0x10ea
k8s.io/client-go/tools/cache.(*Reflector).Run.func1()
	/workspace/go/pkg/mod/k8s.io/client-go@v2.0.0-alpha.0.0.20190115164855-701b91367003+incompatible/tools/cache/reflector.go:133 +0x33
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00006df18)
	/workspace/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190122181752-bebe27e40fb7/pkg/util/wait/wait.go:133 +0x54
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000bd5f18, 0x3b9aca00, 0x0, 0xa30ba01, 0xc0004e0000)
	/workspace/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190122181752-bebe27e40fb7/pkg/util/wait/wait.go:134 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/workspace/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190122181752-bebe27e40fb7/pkg/util/wait/wait.go:88
k8s.io/client-go/tools/cache.(*Reflector).Run(0xc0007adb80, 0xc0004e0000)
	/workspace/go/pkg/mod/k8s.io/client-go@v2.0.0-alpha.0.0.20190115164855-701b91367003+incompatible/tools/cache/reflector.go:132 +0x16b
k8s.io/apimachinery/pkg/util/wait.(*Group).StartWithChannel.func1()
	/workspace/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190122181752-bebe27e40fb7/pkg/util/wait/wait.go:54 +0x2e
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0005fa020, 0xc000502320)
	/workspace/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190122181752-bebe27e40fb7/pkg/util/wait/wait.go:71 +0x4f
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/workspace/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190122181752-bebe27e40fb7/pkg/util/wait/wait.go:69 +0x62

goroutine 31 [select, 5 minutes]:
k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch.func1(0xc0007adb80, 0xc0004e0000, 0xc000652d80, 0xc000890180)
	/workspace/go/pkg/mod/k8s.io/client-go@v2.0.0-alpha.0.0.20190115164855-701b91367003+incompatible/tools/cache/reflector.go:207 +0x150
created by k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch
	/workspace/go/pkg/mod/k8s.io/client-go@v2.0.0-alpha.0.0.20190115164855-701b91367003+incompatible/tools/cache/reflector.go:201 +0xaee

goroutine 12265 [sync.Cond.Wait, 9 minutes]:
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:307
sync.runtime_notifyListWait(0xc001992180, 0xc000000000)
	/usr/local/go/src/runtime/sema.go:510 +0xf9
sync.(*Cond).Wait(0xc001992170)
	/usr/local/go/src/sync/cond.go:56 +0x9e
golang.org/x/net/http2.(*pipe).Read(0xc001992168, 0xc0004ce200, 0x200, 0x200, 0x0, 0x0, 0x0)
	/workspace/go/pkg/mod/golang.org/x/net@v0.0.0-20190613194153-d28f0bde5980/http2/pipe.go:64 +0x8a
golang.org/x/net/http2.transportResponseBody.Read(0xc001992140, 0xc0004ce200, 0x200, 0x200, 0x0, 0x0, 0x0)
	/workspace/go/pkg/mod/golang.org/x/net@v0.0.0-20190613194153-d28f0bde5980/http2/transport.go:1959 +0x95
encoding/json.(*Decoder).refill(0xc000348420, 0xc0002e4000, 0x8)
	/usr/local/go/src/encoding/json/stream.go:159 +0xf8
encoding/json.(*Decoder).readValue(0xc000348420, 0x0, 0x0, 0x428ada0)
	/usr/local/go/src/encoding/json/stream.go:134 +0x210
encoding/json.(*Decoder).Decode(0xc000348420, 0x42f4be0, 0xc000cb40e0, 0x203000, 0x203000)
	/usr/local/go/src/encoding/json/stream.go:63 +0x79
k8s.io/apimachinery/pkg/util/framer.(*jsonFrameReader).Read(0xc0011bc4e0, 0xc000c92000, 0x400, 0x400, 0x38, 0x4454600, 0xc000e2ee18)
	/workspace/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190122181752-bebe27e40fb7/pkg/util/framer/framer.go:150 +0x1a1
k8s.io/apimachinery/pkg/runtime/serializer/streaming.(*decoder).Decode(0xc0000c1d10, 0x0, 0x5903ae0, 0xc000700c00, 0xc000e2ee98, 0xc000e2ef38, 0x42c01a, 0xc000e2eed8, 0x3)
	/workspace/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190122181752-bebe27e40fb7/pkg/runtime/serializer/streaming/streaming.go:77 +0x89
k8s.io/client-go/rest/watch.(*Decoder).Decode(0xc000cb40c0, 0x4d6b488, 0x0, 0x0, 0x0, 0x0, 0x0)
	/workspace/go/pkg/mod/k8s.io/client-go@v2.0.0-alpha.0.0.20190115164855-701b91367003+incompatible/rest/watch/decoder.go:49 +0x7f
k8s.io/apimachinery/pkg/watch.(*StreamWatcher).receive(0xc0011bc540)
	/workspace/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190122181752-bebe27e40fb7/pkg/watch/streamwatcher.go:93 +0x136
created by k8s.io/apimachinery/pkg/watch.NewStreamWatcher
	/workspace/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190122181752-bebe27e40fb7/pkg/watch/streamwatcher.go:60 +0x9f

goroutine 37 [semacquire, 34 minutes]:
sync.runtime_SemacquireMutex(0xc0001c2374, 0x0)
	/usr/local/go/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc0001c2370)
	/usr/local/go/src/sync/mutex.go:134 +0x109
sync.(*RWMutex).Lock(0xc0001c2370)
	/usr/local/go/src/sync/rwmutex.go:93 +0x2d
k8s.io/client-go/tools/cache.(*DeltaFIFO).Resync(0xc0001c2370, 0x0, 0x0)
	/workspace/go/pkg/mod/k8s.io/client-go@v2.0.0-alpha.0.0.20190115164855-701b91367003+incompatible/tools/cache/delta_fifo.go:530 +0x39
k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch.func1(0xc00089d180, 0xc000ed2660, 0xc0004e0120, 0xc000c5e000)
	/workspace/go/pkg/mod/k8s.io/client-go@v2.0.0-alpha.0.0.20190115164855-701b91367003+incompatible/tools/cache/reflector.go:216 +0x1f7
created by k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch
	/workspace/go/pkg/mod/k8s.io/client-go@v2.0.0-alpha.0.0.20190115164855-701b91367003+incompatible/tools/cache/reflector.go:201 +0xaee

goroutine 55 [IO wait, 36 minutes]:
internal/poll.runtime_pollWait(0x7f28e34f5478, 0x77, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc000fe4c78, 0x77, 0xc01, 0xfe00, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitWrite(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:96
internal/poll.(*FD).Write(0xc000fe4c60, 0xc001a6a000, 0x10cce, 0x1fe00, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:276 +0x26e
os.(*File).write(...)
	/usr/local/go/src/os/file_unix.go:280
os.(*File).Write(0xc00011aa78, 0xc001a6a000, 0x10cce, 0x1fe00, 0x0, 0x0, 0x0)
	/usr/local/go/src/os/file.go:145 +0x76
github.com/jenkins-x/jx/pkg/cloud/gke.pipeBytes(0x5905fe0, 0xc000f39e00, 0xc001a6a000, 0x10cce, 0x1fe00, 0x0, 0x0)
	/workspace/source/pkg/cloud/gke/gcloud.go:421 +0x85
github.com/jenkins-x/jx/pkg/cloud/gke.UploadFileToBucket(0xc001a6a000, 0x10cce, 0x1fe00, 0xc00196b920, 0x2f, 0xc00079de60, 0x1b, 0x0, 0x44ebfc0, 0xc00148af01, ...)
	/workspace/source/pkg/cloud/gke/gcloud.go:412 +0x2b9
github.com/jenkins-x/jx/pkg/cloud/gke/storage.(*GKEBucketProvider).UploadFileToBucket(0xc000f53100, 0x58cf960, 0xc000f39c80, 0xc00196b920, 0x2f, 0xc00079de60, 0x1b, 0x0, 0x0, 0x0, ...)
	/workspace/source/pkg/cloud/gke/storage/bucket_provider.go:82 +0xcd
github.com/jenkins-x/jx/pkg/collector.(*BucketCollector).CollectData(0xc00072d040, 0xc001af8000, 0x10cce, 0x12000, 0xc00196b920, 0x2f, 0x591fc60, 0xc000461830, 0xc000c4cf5c, 0x2)
	/workspace/source/pkg/collector/bucket_collector.go:71 +0xc5
github.com/jenkins-x/jx/pkg/cmd/controller.(*ControllerBuildOptions).generateBuildLogURL(0xc000358690, 0x599bcc0, 0xc000cafd60, 0xc000c4cf5c, 0x2, 0xc000b11200, 0xc0008afbc0, 0x22, 0xc001596000, 0xc0011bf238, ...)
	/workspace/source/pkg/cmd/controller/controller_build.go:1114 +0x786
github.com/jenkins-x/jx/pkg/cmd/controller.(*ControllerBuildOptions).updatePipelineActivityForRun(0xc000358690, 0x59e31a0, 0xc000938600, 0xc000c4cf5c, 0x2, 0xc000b11200, 0xc001549d40, 0xc001596000, 0x0)
	/workspace/source/pkg/cmd/controller/controller_build.go:773 +0xc00
github.com/jenkins-x/jx/pkg/cmd/controller.(*ControllerBuildOptions).onPipelinePod.func1(0xc001497f20, 0xc000854f00)
	/workspace/source/pkg/cmd/controller/controller_build.go:363 +0x2bf
github.com/cenkalti/backoff.RetryNotify(0xc000de5a38, 0x58fb7e0, 0xc001497f20, 0x0, 0x0, 0x0)
	/workspace/go/pkg/mod/github.com/cenkalti/backoff@v2.1.1+incompatible/retry.go:37 +0xb9
github.com/cenkalti/backoff.Retry(...)
	/workspace/go/pkg/mod/github.com/cenkalti/backoff@v2.1.1+incompatible/retry.go:24
github.com/jenkins-x/jx/pkg/util.Retry(0x4a817c800, 0xc0015cba38, 0x2, 0x5981060)
	/workspace/source/pkg/util/retry.go:14 +0xa4
github.com/jenkins-x/jx/pkg/cmd/controller.(*ControllerBuildOptions).onPipelinePod(0xc000358690, 0x48a0720, 0xc001596000, 0x59e31a0, 0xc000938600, 0x591fbe0, 0xc001090240, 0x5920ba0, 0xc000c65690, 0xc000c4cf5c, ...)
	/workspace/source/pkg/cmd/controller/controller_build.go:353 +0x9a2
github.com/jenkins-x/jx/pkg/cmd/controller.(*ControllerBuildOptions).Run.func2(0x48a0720, 0xc000aba000, 0x48a0720, 0xc001596000)
	/workspace/source/pkg/cmd/controller/controller_build.go:213 +0x8d
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnUpdate(...)
	/workspace/go/pkg/mod/k8s.io/client-go@v2.0.0-alpha.0.0.20190115164855-701b91367003+incompatible/tools/cache/controller.go:202
k8s.io/client-go/tools/cache.NewInformer.func1(0x43349e0, 0xc000fecee0, 0x1, 0xc000fecee0)
	/workspace/go/pkg/mod/k8s.io/client-go@v2.0.0-alpha.0.0.20190115164855-701b91367003+incompatible/tools/cache/controller.go:309 +0x299
k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc0001c2370, 0xc000b9a120, 0x0, 0x0, 0x0, 0x0)
	/workspace/go/pkg/mod/k8s.io/client-go@v2.0.0-alpha.0.0.20190115164855-701b91367003+incompatible/tools/cache/delta_fifo.go:444 +0x215
k8s.io/client-go/tools/cache.(*controller).processLoop(0xc0008a2600)
	/workspace/go/pkg/mod/k8s.io/client-go@v2.0.0-alpha.0.0.20190115164855-701b91367003+incompatible/tools/cache/controller.go:150 +0x40
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000b97fb0)
	/workspace/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190122181752-bebe27e40fb7/pkg/util/wait/wait.go:133 +0x54
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000de5fb0, 0x3b9aca00, 0x0, 0xc000ca0a01, 0xc000ed2660)
	/workspace/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190122181752-bebe27e40fb7/pkg/util/wait/wait.go:134 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/workspace/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190122181752-bebe27e40fb7/pkg/util/wait/wait.go:88
k8s.io/client-go/tools/cache.(*controller).Run(0xc0008a2600, 0xc000ed2660)
	/workspace/go/pkg/mod/k8s.io/client-go@v2.0.0-alpha.0.0.20190115164855-701b91367003+incompatible/tools/cache/controller.go:124 +0x2a8
created by github.com/jenkins-x/jx/pkg/cmd/controller.(*ControllerBuildOptions).Run
	/workspace/source/pkg/cmd/controller/controller_build.go:221 +0x816

goroutine 56 [chan receive, 123 minutes]:
k8s.io/client-go/tools/cache.(*controller).Run.func1(0xc000ed2660, 0xc0008a2600)
	/workspace/go/pkg/mod/k8s.io/client-go@v2.0.0-alpha.0.0.20190115164855-701b91367003+incompatible/tools/cache/controller.go:103 +0x34
created by k8s.io/client-go/tools/cache.(*controller).Run
	/workspace/go/pkg/mod/k8s.io/client-go@v2.0.0-alpha.0.0.20190115164855-701b91367003+incompatible/tools/cache/controller.go:102 +0x92

goroutine 57 [semacquire, 32 minutes]:
sync.runtime_SemacquireMutex(0xc0001c2374, 0xc001434500)
	/usr/local/go/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc0001c2370)
	/usr/local/go/src/sync/mutex.go:134 +0x109
sync.(*RWMutex).Lock(0xc0001c2370)
	/usr/local/go/src/sync/rwmutex.go:93 +0x2d
k8s.io/client-go/tools/cache.(*DeltaFIFO).Add(0xc0001c2370, 0x48a0720, 0xc0013f2380, 0x0, 0x0)
	/workspace/go/pkg/mod/k8s.io/client-go@v2.0.0-alpha.0.0.20190115164855-701b91367003+incompatible/tools/cache/delta_fifo.go:174 +0x39
k8s.io/client-go/tools/cache.(*Reflector).watchHandler(0xc00089d180, 0x59040e0, 0xc000c96990, 0xc000bd3bb0, 0xc000c5e000, 0xc000ed2660, 0x0, 0x0)
	/workspace/go/pkg/mod/k8s.io/client-go@v2.0.0-alpha.0.0.20190115164855-701b91367003+incompatible/tools/cache/reflector.go:326 +0x594
k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch(0xc00089d180, 0xc000ed2660, 0x0, 0x0)
	/workspace/go/pkg/mod/k8s.io/client-go@v2.0.0-alpha.0.0.20190115164855-701b91367003+incompatible/tools/cache/reflector.go:268 +0x10ea
k8s.io/client-go/tools/cache.(*Reflector).Run.func1()
	/workspace/go/pkg/mod/k8s.io/client-go@v2.0.0-alpha.0.0.20190115164855-701b91367003+incompatible/tools/cache/reflector.go:133 +0x33
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00006f718)
	/workspace/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190122181752-bebe27e40fb7/pkg/util/wait/wait.go:133 +0x54
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000bd3f18, 0x3b9aca00, 0x0, 0xa30ba01, 0xc000ed2660)
	/workspace/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190122181752-bebe27e40fb7/pkg/util/wait/wait.go:134 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/workspace/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190122181752-bebe27e40fb7/pkg/util/wait/wait.go:88
k8s.io/client-go/tools/cache.(*Reflector).Run(0xc00089d180, 0xc000ed2660)
	/workspace/go/pkg/mod/k8s.io/client-go@v2.0.0-alpha.0.0.20190115164855-701b91367003+incompatible/tools/cache/reflector.go:132 +0x16b
k8s.io/apimachinery/pkg/util/wait.(*Group).StartWithChannel.func1()
	/workspace/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190122181752-bebe27e40fb7/pkg/util/wait/wait.go:54 +0x2e
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0008a4030, 0xc0008a0360)
	/workspace/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190122181752-bebe27e40fb7/pkg/util/wait/wait.go:71 +0x4f
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/workspace/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190122181752-bebe27e40fb7/pkg/util/wait/wait.go:69 +0x62

goroutine 12209 [chan send, 32 minutes]:
k8s.io/apimachinery/pkg/watch.(*StreamWatcher).receive(0xc000c96990)
	/workspace/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190122181752-bebe27e40fb7/pkg/watch/streamwatcher.go:114 +0x11c
created by k8s.io/apimachinery/pkg/watch.NewStreamWatcher
	/workspace/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190122181752-bebe27e40fb7/pkg/watch/streamwatcher.go:60 +0x9f
```

**Comment by jstrachan** [comment]
probably the same as https://github.com/jenkins-x/jx/issues/6217
