### ISSUE TITLE
bitbucket credentials not found/used when trying to update build status

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#665]
I just tried building a PR on a bitbucket repo in Jenkins X and got the following error. It looks like the Credential thats setup for bitbucket isn't being used properly (its a username/password credential).

I wonder if we need to configure the Credential so it is better discovered by the [bitbucket branch source plugin](https://github.com/jenkinsci/bitbucket-branch-source-plugin)? 

Maybe the kubernetes-credentials-provider needs to expose the server URL the credential is for or something so it can be found by the plugin? 
https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/master/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketCredentials.java#L47

```
[Bitbucket] Notifying pull request build result
ERROR: Could not send notifications
java.io.IOException: Communication error
	at com.cloudbees.jenkins.plugins.bitbucket.client.BitbucketCloudApiClient.doRequest(BitbucketCloudApiClient.java:771)
	at com.cloudbees.jenkins.plugins.bitbucket.client.BitbucketCloudApiClient.postRequest(BitbucketCloudApiClient.java:812)
	at com.cloudbees.jenkins.plugins.bitbucket.client.BitbucketCloudApiClient.postBuildStatus(BitbucketCloudApiClient.java:530)
	at com.cloudbees.jenkins.plugins.bitbucket.BitbucketChangesetCommentNotifier.buildStatus(BitbucketChangesetCommentNotifier.java:51)
	at com.cloudbees.jenkins.plugins.bitbucket.BitbucketBuildStatusNotifications.createStatus(BitbucketBuildStatusNotifications.java:93)
	at com.cloudbees.jenkins.plugins.bitbucket.BitbucketBuildStatusNotifications.sendNotifications(BitbucketBuildStatusNotifications.java:118)
	at com.cloudbees.jenkins.plugins.bitbucket.BitbucketBuildStatusNotifications.access$000(BitbucketBuildStatusNotifications.java:55)
	at com.cloudbees.jenkins.plugins.bitbucket.BitbucketBuildStatusNotifications$JobCompletedListener.onCompleted(BitbucketBuildStatusNotifications.java:166)
	at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:211)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.finish(WorkflowRun.java:688)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.access$1400(WorkflowRun.java:143)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun$GraphL.onNewHead(WorkflowRun.java:1006)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.notifyListeners(CpsFlowExecution.java:1368)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$3.run(CpsThreadGroup.java:412)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$1.run(CpsVmExecutorService.java:35)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.http.NoHttpResponseException: api.bitbucket.org:443 failed to respond
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:141)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at com.cloudbees.jenkins.plugins.bitbucket.client.BitbucketCloudApiClient.executeMethod(BitbucketCloudApiClient.java:669)
	at com.cloudbees.jenkins.plugins.bitbucket.client.BitbucketCloudApiClient.doRequest(BitbucketCloudApiClient.java:753)
	... 21 more
Finished: SUCCESS
```

**Comment by cyrille-leclerc** [comment]
> Maybe the kubernetes-credentials-provider needs to expose the server URL the credential is for or something so it can be found by the plugin?

I don't think so, the bitbucket server URL is used in this class to filter credentials based on the "requirements" of the credentials domain.
kubernetes-credentials-provider creates a standard "unrestricted domain" called "Global credentials (unrestricted)"

![](https://snag.gy/S5ZWsI.jpg)

**Comment by jstrachan** [comment]
BTW here's the YAML of the Secret which works for browsing owners/repos in the Jenkins UI but not for the notification of build completion/failure inside the pipeline:
```yaml
apiVersion: v1
type: Opaque
kind: Secret
metadata:
  annotations:
    jenkins.io/credentials-description: API Token for acccessing https://bitbucket.org git service inside pipelines
    jenkins.io/name: bitbucket
    jenkins.io/url: https://bitbucket.org
  labels:
    jenkins.io/created-by: jx
    jenkins.io/credentials-type: usernamePassword
    jenkins.io/kind: git
    jenkins.io/service-kind: bitbucket
  name: jx-pipeline-git-bitbucket-bitbucket
data:
  password: XXXXX
  username: XXXX
```

**Comment by jstrachan** [comment]
@cyrille-leclerc dunno if its related but in Jenkins X with the kubernetes-credentails-provider plugin we get 2 global scopes with different icons (looks like the  kubernetes-credentails-provider plugin  uses a different global scope)?:

<img width="1176" alt="jenkins_ _credentials__jenkins_" src="https://user-images.githubusercontent.com/30140/38932354-e11c3cae-430d-11e8-8d18-146f5fc6f0a8.png">

**Comment by jtnord** [comment]
@jstrachan they are different stores so you are seeing the global scope in each of the store.

**Comment by cyrille-leclerc** [comment]
The UI is a bit tricky to understand but it looks good to me:

* 2 stores declared at the global level (ie "Jenkins" level)
   * Jenkins native file based store
   * Kubernetes based store
* Most of the credentials are declared in the Kubernetes store, including jx-pipeline-git-bitbucket-bitbucket
* jx-pipeline-git-bitbucket-bitbucket seems to be username/password credentials as custom-bitbucket credentials are.

**Comment by jtnord** [comment]
@jstrachan can you use the credential in a pipeline with credentialBinding and just echo the env vars (to make sure the credential is correctly found)  if so then this is likely an issue with the bitbucket plugin.

**Comment by jstrachan** [comment]
yeah - the kubernetes-credentials provider credential works fine everywhere I've used it - apart from in gitea + bitbucket branch source plugins when they try to notify build results. Kinda wacky! Just trying to figure out why this seemingly working Credential can't be used for notifying build results

**Comment by jstrachan** [comment]
@jtnord yeah - can use the kubernetes-credential just fine [inside a pipeline](https://bitbucket.org/jstrachan/environment-jx-staging-bb2/src/4e43f43686adda8257c294ce6928125eb192d712/Jenkinsfile?at=master&fileviewer=file-view-default#Jenkinsfile-7)

**Comment by jstrachan** [comment]
here's the support bundle for Jenkins X when the kubernetes credentails plugin definitely doesn't work with BitBucket / Gitea:
[support_2018-04-20_14.25.05.zip](https://github.com/jenkins-x/jx/files/1932473/support_2018-04-20_14.25.05.zip)

**Comment by jtnord** [comment]
not sure what the issue was but it is working fine when I just tried it in the jx env.

Now the response was a no data from server - which I doubt would be the case if the credential was wrong or not provided at all, possibly infra related on bitbucket or k8s egress side?

**Comment by jstrachan** [comment]
@jtnord any chance you could type `jx version` so I could see what permutation of versions worked for you? What kind of k8s cluster was it - GKE?

**Comment by jtnord** [comment]
@jstrachan I was using your cdx cluster, the one you put in hipchat for @sarch.

**Comment by jstrachan** [comment]
Seems to have magically fixed itself - odd!!!
