### ISSUE TITLE
non-boot clusters nil pointer on `jx step helm apply`

### ISSUE THREAD

**Issue by abayer** [jenkins-x/jx#6812]
Note that this isn't in the version stream - it's caused by #6771, and is in fact causing the version stream update to fail.

The staging (and production) env pipelines in a `jx install` cluster with Tekton (not with static masters - we caught that problem before #6771 was merged, but due to #6811 we didn't catch the Tekton case) will fail with an error like:

```
Showing logs for build jenkins-x-versions-bot-test-env-hj4rl-1 stage from-build-pack and container step-build-helm-apply
Modified file /workspace/source/env/Chart.yaml to set the chart to version 1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x248 pc=0x26dafd3]

goroutine 1 [running]:
github.com/jenkins-x/**/pkg/cmd/step/helm.(*StepHelmApplyOptions).Run(0xc00083b290, 0x0, 0x0)
	/workspace/source/pkg/cmd/step/helm/step_helm_apply.go:255 +0xde3
github.com/jenkins-x/**/pkg/cmd/step/helm.NewCmdStepHelmApply.func1(0xc0009d4c80, 0xa733d88, 0x0, 0x0)
	/workspace/source/pkg/cmd/step/helm/step_helm_apply.go:85 +0x6f
github.com/spf13/cobra.(*Command).execute(0xc0009d4c80, 0xa733d88, 0x0, 0x0, 0xc0009d4c80, 0xa733d88)
	/workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0xc000493680, 0xc0005bfc00, 0x5ace800, 0xc0000b8000)
	/workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
	/workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/jenkins-x/**/cmd/**/app.Run(0x0, 0x0, 0x0, 0xc0008a3f88, 0xc00009e058)
	/workspace/source/cmd/**/app/**.go:19 +0x185
main.main()
	/workspace/source/cmd/**/**.go:11 +0x32
```

This is because we end up getting a nil `requirements`. We special-case static masters currently, but we really need to handle all cases where we're on a `jx install` cluster the same in this regard.

**Comment by abayer** [comment]
https://github.com/abayer/jx/commit/9fb29e1117ad181b9f3243970e3bf4d1b32cd787 maaaaay fix it. I did reproduce the failure in #6813, but I'm waiting for it to fully fail before I try the fix on that PR.

**Comment by abayer** [comment]
https://github.com/jenkins-x/jx/pull/6813/commits/0e77134aa7075055a2887330335015d3377cc0a5 fixes at least the `tekton` context - waiting for both the `tekton` and `bdd` context to pass to be sure.
