### ISSUE TITLE
Panic during jx create spring

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#715]
Using:

> NAME               VERSION
> jx                 1.2.20
> jenkins x platform 0.0.795
> kubernetes cluster v1.9.3-gke.0
> kubectl            v1.9.6
> helm client        v2.8.2+ga802316
> helm server        v2.8.2+ga802316
> git                git version 2.15.1 (Apple Git-101)

Actions:
`jx create spring -t 1.5.12.RELEASE -d web -d actuator`

```
About to create repository deleteme20 on server github.com with user dvsbot
? Which organisation do you want to use? dvsbot
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x16dba8a]

goroutine 1 [running]:
github.com/jenkins-x/jx/pkg/gits.(*GitHubProvider).ValidateRepositoryName(0xc42058a240, 0xc420447310, 0x6, 0xc42033a04c, 0xa, 0x1f, 0xc42033a04c)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/gits/github.go:536 +0x9a
github.com/jenkins-x/jx/pkg/gits.PickNewGitRepository.func2(0x23c5ce0, 0xc4205534a0, 0xc4205534a0, 0x0)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/gits/git_repo.go:144 +0x128
github.com/jenkins-x/jx/vendor/gopkg.in/AlecAivazis/survey%2ev1.Ask(0xc42084d648, 0x1, 0x1, 0x2376be0, 0xc420553360, 0x30, 0x251e2c0)
	/home/jenkins/go/src/github.com/jenkins-x/jx/vendor/gopkg.in/AlecAivazis/survey.v1/survey.go:105 +0x1d9
github.com/jenkins-x/jx/vendor/gopkg.in/AlecAivazis/survey%2ev1.AskOne(0x32ee680, 0xc42031e400, 0x2376be0, 0xc420553360, 0xc42060f020, 0x0, 0x0)
	/home/jenkins/go/src/github.com/jenkins-x/jx/vendor/gopkg.in/AlecAivazis/survey.v1/survey.go:54 +0xbe
github.com/jenkins-x/jx/pkg/gits.PickNewGitRepository(0x32df980, 0xc42000c018, 0xc42033a000, 0xc42033cf80, 0x1d, 0xc420281f80, 0xc42033a04c, 0xa, 0xc4200b43e8, 0xc420526120, ...)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/gits/git_repo.go:146 +0xbfc
github.com/jenkins-x/jx/pkg/jx/cmd.(*ImportOptions).CreateNewRemoteRepository(0xc4200b42c0, 0x0, 0x0)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/import.go:549 +0x172
github.com/jenkins-x/jx/pkg/jx/cmd.(*ImportOptions).Run(0xc4200b42c0, 0x0, 0x0)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/import.go:328 +0x46f
github.com/jenkins-x/jx/pkg/jx/cmd.(*CreateProjectOptions).ImportCreatedProject(0xc4200b42c0, 0xc42033a030, 0x26, 0xc42057dc48, 0x1)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/create.go:99 +0x6a
github.com/jenkins-x/jx/pkg/jx/cmd.(*CreateSpringOptions).Run(0xc4200b42c0, 0xc42006bc50, 0x0)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/create_spring.go:123 +0x2f2
github.com/jenkins-x/jx/pkg/jx/cmd.NewCmdCreateSpring.func1(0xc420156000, 0xc42014ae40, 0x0, 0x6)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/create_spring.go:71 +0x75
github.com/jenkins-x/jx/vendor/github.com/spf13/cobra.(*Command).execute(0xc420156000, 0xc42014ade0, 0x6, 0x6, 0xc420156000, 0xc42014ade0)
	/home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/jenkins-x/jx/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4200c4f00, 0xc420157180, 0xc42060cf00, 0xc4204a4500)
	/home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/spf13/cobra/command.go:852 +0x334
github.com/jenkins-x/jx/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4200c4f00, 0xc42074d6c0, 0x32df900)
	/home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/jenkins-x/jx/cmd/jx/app.Run(0xc4204ebf70, 0x228a429)
	/home/jenkins/go/src/github.com/jenkins-x/jx/cmd/jx/app/jx.go:18 +0x90
main.main()
	/home/jenkins/go/src/github.com/jenkins-x/jx/cmd/jx/jx.go:10 +0x22
```

**Comment by tdcox** [comment]
Looks like this may be an artefact of upgrading. When running the script, I was asked:
````
Which git service do you want to use
github.com
https://github.com
````

I chose the first and it used the git token from my previous install and eventually failed as above. I have then subsequently tried again using the second selection and found that it asked me for a new API Token and then went on to deploy sucessfully without the above error.
