### ISSUE TITLE
JNLP Windows JNLP container cannot connect to jenkins master and then gets terminated after a few minutes

### ISSUE THREAD

**Issue by nkchand91** [jenkins-x/jx#7208]
### Summary 
I am connecting a windows slave to Jenkins Master(Linux) server via JNLP protocol

### Expected behavior
JNLP container should connect MAster

### Actual behavior
JNLP Windows JNLP container cannot connect to jenkins master and then gets terminated after a few minutes
```
COPY OUTPUT HERE
```
java.net.UnknownHostException: http
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
        at java.net.PlainSocketImpl.connect(Unknown Source)
        at java.net.SocksSocketImpl.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at sun.net.NetworkClient.doConnect(Unknown Source)
        at sun.net.www.http.HttpClient.openServer(Unknown Source)
        at sun.net.www.http.HttpClient.openServer(Unknown Source)
        at sun.net.www.http.HttpClient.<init>(Unknown Source)
        at sun.net.www.http.HttpClient.New(Unknown Source)
        at sun.net.www.http.HttpClient.New(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
        at hudson.remoting.Launcher.parseJnlpArguments(Launcher.java:513)
        at hudson.remoting.Launcher.run(Launcher.java:347)
        at hudson.remoting.Launcher.main(Launcher.java:298)
Waiting 10 seconds before retry

### Operating system / Environment
Windows 7 enterprise as slave

**Comment by deanesmith** [comment]
Hi @nkchand91, It appears this issue may not be related to Jenkins-X, but rather Jenkins.  You can raise an issue in that org if this is the case - https://github.com/jenkinsci/jenkins
