### ISSUE TITLE
Panic during jx gitops upgrade

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#7742]
```
➜ jx gitops upgrade
upgrading local source code from the version stream using kpt...

no strategy configuration file .jx/gitops/kpt-strategy.yaml found so using default merge strategies
processing kpt directory: .jx/secret/mapping wth strategy: alpha-git-patch
processing kpt directory: .lighthouse/jenkins-x wth strategy: alpha-git-patch
processing kpt directory: versionStream wth strategy: force-delete-replace

now checking the chart versions in helmfile.yaml

Installing plugin helm version 3.5.3 for command jx helm from https://get.helm.sh/helm-v3.5.3-darwin-amd64.tar.gz into /Users/terry/.jx/plugins/bin
using helm binary /Users/terry/.jx/plugins/bin/helm-3.5.3 to verify chart repositories
Installing plugin helmfile version 0.138.7 for command jx helmfile from https://github.com/roboll/helmfile/releases/download/v0.138.7/helmfile_darwin_amd64 into /Users/terry/.jx/plugins/bin
error: failed to resolve helmfile: failed to update the helmfile versions: failed to run command /Users/terry/.jx/plugins/bin/helmfile-0.138.7 repos in dir : failed to run '/Users/terry/.jx/plugins/bin/helmfile-0.138.7 repos' command in directory '', output: 'panic: unexpected error: exec: "helm": executable file not found in $PATH

goroutine 1 [running]:
github.com/roboll/helmfile/pkg/helmexec.Output(0xc00051d4a0, 0xc0006ba858, 0x1, 0x1, 0xc000700400, 0x34, 0x40, 0x203c5c0, 0x0)
	/home/circleci/workspace/helmfile/pkg/helmexec/runner.go:95 +0xae4
github.com/roboll/helmfile/pkg/helmexec.ShellRunner.Execute(0x0, 0x0, 0xc00000e018, 0x22ef360, 0x4, 0xc0005d2090, 0x3, 0x3, 0x0, 0x100c9a8, ...)
	/home/circleci/workspace/helmfile/pkg/helmexec/runner.go:40 +0x121
github.com/roboll/helmfile/pkg/helmexec.getHelmVersion(0x22ef360, 0x4, 0x28c8f40, 0xc0004a6b60, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/circleci/workspace/helmfile/pkg/helmexec/exec.go:77 +0xff
github.com/roboll/helmfile/pkg/helmexec.New(0x22ef360, 0x4, 0xc00000e018, 0x0, 0x0, 0x28c8f40, 0xc0004a6b60, 0x0)
	/home/circleci/workspace/helmfile/pkg/helmexec/exec.go:88 +0x67
github.com/roboll/helmfile/pkg/app.(*App).getHelm(0xc00020e5a0, 0xc0002a0a00, 0x0, 0x0)
	/home/circleci/workspace/helmfile/pkg/app/app.go:664 +0x261
github.com/roboll/helmfile/pkg/app.(*App).visitStatesWithSelectorsAndRemoteSupport.func1(0xc0002a0a00, 0xc0002a0a00, 0x0, 0x0, 0xc0002a0780)
	/home/circleci/workspace/helmfile/pkg/app/app.go:923 +0x41
github.com/roboll/helmfile/pkg/app.(*App).visitStates.func1(0xc0001ac857, 0xd, 0xc000010000, 0x62, 0x0, 0x0)
	/home/circleci/workspace/helmfile/pkg/app/app.go:763 +0x7ec
github.com/roboll/helmfile/pkg/app.(*App).visitStateFiles.func1(0xc000034230, 0x4b)
	/home/circleci/workspace/helmfile/pkg/app/app.go:596 +0x9d
github.com/roboll/helmfile/pkg/app.(*App).within(0xc00020e5a0, 0xc0001ac840, 0x16, 0xc0006bb230, 0xc0006bb1f0, 0x2)
	/home/circleci/workspace/helmfile/pkg/app/app.go:557 +0x33e
github.com/roboll/helmfile/pkg/app.(*App).visitStateFiles(0xc00020e5a0, 0xc0001ac840, 0x24, 0x33c37b0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/circleci/workspace/helmfile/pkg/app/app.go:590 +0x2f2
github.com/roboll/helmfile/pkg/app.(*App).visitStates(0xc00020e5a0, 0xc0001ac840, 0x24, 0x33c37b0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/circleci/workspace/helmfile/pkg/app/app.go:675 +0x10b
github.com/roboll/helmfile/pkg/app.(*App).visitStates.func1.2(0xc000000068, 0x234f490)
	/home/circleci/workspace/helmfile/pkg/app/app.go:735 +0x31c
github.com/roboll/helmfile/pkg/app.(*App).visitStates.func1(0x22fa32c, 0xd, 0xc000198640, 0x34, 0x0, 0x0)
	/home/circleci/workspace/helmfile/pkg/app/app.go:752 +0x916
github.com/roboll/helmfile/pkg/app.(*App).visitStateFiles.func1(0x0, 0x22ee115)
	/home/circleci/workspace/helmfile/pkg/app/app.go:596 +0x9d
github.com/roboll/helmfile/pkg/app.(*App).within(0xc00020e5a0, 0x22ee115, 0x1, 0xc0006bbc18, 0xc0006bbbd8, 0x2)
	/home/circleci/workspace/helmfile/pkg/app/app.go:538 +0x602
github.com/roboll/helmfile/pkg/app.(*App).visitStateFiles(0xc00020e5a0, 0x0, 0x0, 0x33c37b0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/circleci/workspace/helmfile/pkg/app/app.go:590 +0x2f2
github.com/roboll/helmfile/pkg/app.(*App).visitStates(0xc00020e5a0, 0x0, 0x0, 0x33c37b0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/circleci/workspace/helmfile/pkg/app/app.go:675 +0x10b
github.com/roboll/helmfile/pkg/app.(*App).visitStatesWithSelectorsAndRemoteSupport(0xc00020e5a0, 0x0, 0x0, 0xc0006bbf38, 0xc0006bbfa0, 0x1, 0x1, 0x1, 0xc000038110)
	/home/circleci/workspace/helmfile/pkg/app/app.go:930 +0x4c1
github.com/roboll/helmfile/pkg/app.(*App).ForEachState(0xc00020e5a0, 0xc0006bbfa8, 0xc0006bbfa0, 0x1, 0x1, 0x22d4c00, 0xc00078c810)
	/home/circleci/workspace/helmfile/pkg/app/app.go:811 +0xb2
github.com/roboll/helmfile/pkg/app.(*App).Repos(0xc00020e5a0, 0x28bdf60, 0xc00078c810, 0xc00078c810, 0xc00000e018)
	/home/circleci/workspace/helmfile/pkg/app/app.go:123 +0xa9
main.main.func2(0xc00020e5a0, 0xc0001e42c0, 0x0, 0xc00078c7c0, 0x0)
	/home/circleci/workspace/helmfile/main.go:140 +0x6d
main.action.func1(0xc0001e42c0, 0x0, 0xc0008229d0)
	/home/circleci/workspace/helmfile/main.go:793 +0xd4
github.com/urfave/cli.HandleAction(0x204baa0, 0xc00078c070, 0xc0001e42c0, 0xc0001e42c0, 0x0)
	/home/circleci/workspace/helmfile/vendor/github.com/urfave/cli/app.go:524 +0x11a
github.com/urfave/cli.Command.Run(0x22f0aad, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x2339cdb, 0x45, 0x0, ...)
	/home/circleci/workspace/helmfile/vendor/github.com/urfave/cli/command.go:173 +0x57a
github.com/urfave/cli.(*App).Run(0xc00060c700, 0xc00019a000, 0x2, 0x2, 0x0, 0x0)
	/home/circleci/workspace/helmfile/vendor/github.com/urfave/cli/app.go:277 +0x7c7
main.main()
	/home/circleci/workspace/helmfile/main.go:564 +0x3dce'
```

**Comment by jstrachan** [comment]
looks like helmfile now expects `helm` on the `$PATH` and `jx gitops upgrade` doesn’t automatically add it. Its probably simplest to enable auto upgrades which then runs it inside k8s with images with all the binaries required on the PATH: https://jenkins-x.io/v3/admin/setup/upgrades/cluster/#automatic-upgrades

a workaround is to copy the file `~/.jx/plugins/bin/helm-*` to `helm` somewhere on your `$PATH` - or download an install `helm` yourself
