### ISSUE TITLE
Segmentation violation during deployment of preview

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#931]
Using:

> NAME               VERSION
> jx                 1.2.88
> jenkins x platform 0.0.1109
> kubernetes cluster v1.9.7-gke.1
> kubectl            v1.9.6
> helm client        v2.9.0+gf6025bb
> helm server        v2.9.0+gf6025bb
> git                git version 2.15.1 (Apple Git-101)

Actions:
Commit a change to an existing PR deployed as a preview environment and push.

```
[Pipeline] sh
[preview] Running shell script

+ jx preview --app face-service --dir ../..
Executing preview w/log.Info...
Commit author email is empty for: 9bc5aa906fcd36b0b1c1a3fb16a0dd95b2a0a2b0
Looking for commits in: /home/jenkins/workspace/DVSJersey_face-service_PR-1-72FIDXVGOXBILW6VEJU7N7OXTSTGH5UOVGEMSLXHP7OXSZUP7EOA/
Commit author email is empty for: 3d124c17cc5bfb12ded17d9f3d614c0aaa68346b
Looking for commits in: /home/jenkins/workspace/DVSJersey_face-service_PR-1-72FIDXVGOXBILW6VEJU7N7OXTSTGH5UOVGEMSLXHP7OXSZUP7EOA/
Commit author email is empty for: 1ce80f38bf7358546692fe54efc12348d6e2854c
Looking for commits in: /home/jenkins/workspace/DVSJersey_face-service_PR-1-72FIDXVGOXBILW6VEJU7N7OXTSTGH5UOVGEMSLXHP7OXSZUP7EOA/
Commit author email is empty for: 0559d8b21f50a550c7d3246e8f92793cdf873ec2
Looking for commits in: /home/jenkins/workspace/DVSJersey_face-service_PR-1-72FIDXVGOXBILW6VEJU7N7OXTSTGH5UOVGEMSLXHP7OXSZUP7EOA/
Commit author email is empty for: 12605e0988d76b9849bf3a4921f52d55f688e1ef
Looking for commits in: /home/jenkins/workspace/DVSJersey_face-service_PR-1-72FIDXVGOXBILW6VEJU7N7OXTSTGH5UOVGEMSLXHP7OXSZUP7EOA/
Commit author email is empty for: 94a65585bbabdbfd851853b37e206702184711d8
Looking for commits in: /home/jenkins/workspace/DVSJersey_face-service_PR-1-72FIDXVGOXBILW6VEJU7N7OXTSTGH5UOVGEMSLXHP7OXSZUP7EOA/
Commit author email is empty for: cafac3091c532ca7ca1429d13fb9eece931b3c20
Looking for commits in: /home/jenkins/workspace/DVSJersey_face-service_PR-1-72FIDXVGOXBILW6VEJU7N7OXTSTGH5UOVGEMSLXHP7OXSZUP7EOA/
Commit author email is empty for: 6804fa5aa5484191ba24a089666b472c95bfa241
Looking for commits in: /home/jenkins/workspace/DVSJersey_face-service_PR-1-72FIDXVGOXBILW6VEJU7N7OXTSTGH5UOVGEMSLXHP7OXSZUP7EOA/
Commit author email is empty for: 70603cf2920500f04e8c7c00979f903a7abcfdcf
Looking for commits in: /home/jenkins/workspace/DVSJersey_face-service_PR-1-72FIDXVGOXBILW6VEJU7N7OXTSTGH5UOVGEMSLXHP7OXSZUP7EOA/
PullRequest author email is empty
Found commit author match for: tdcox with email address: terry@bootstrap.je
CreateOrUpdateUser: tdcox <terry@bootstrap.je>
Existing user found: terry@bootstrap.je
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xa0 pc=0x1667cf0]

goroutine 1 [running]:
github.com/jenkins-x/jx/pkg/jx/cmd.(*PreviewOptions).Run(0xc420681680, 0xc420059c50, 0x0)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/preview.go:288 +0x28b0
github.com/jenkins-x/jx/pkg/jx/cmd.NewCmdPreview.func1(0xc420681900, 0xc4202ec480, 0x0, 0x4)
	/home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/preview.go:91 +0x75
github.com/jenkins-x/jx/vendor/github.com/spf13/cobra.(*Command).execute(0xc420681900, 0xc4202ec440, 0x4, 0x4, 0xc420681900, 0xc4202ec440)
	/home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/jenkins-x/jx/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4200b0c80, 0xc4202b3b80, 0xc420557680, 0xc420750000)
	/home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/spf13/cobra/command.go:852 +0x334
github.com/jenkins-x/jx/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4200b0c80, 0xc420778240, 0x2799a40)
	/home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/jenkins-x/jx/cmd/jx/app.Run(0xc4207a1f70, 0x16dd5a9)
	/home/jenkins/go/src/github.com/jenkins-x/jx/cmd/jx/app/jx.go:18 +0x90
main.main()
	/home/jenkins/go/src/github.com/jenkins-x/jx/cmd/jx/jx.go:10 +0x22
```

I note that in the previous build, the user seems to have been created:

```
PullRequest author email is empty
Found commit author match for: tdcox with email address: terry@bootstrap.je
CreateOrUpdateUser: tdcox <terry@bootstrap.je>
Unable to find user: terry.bootstrap.je -- users.jenkins.io "terry.bootstrap.je" not found
Adding missing user: terry.bootstrap.je
```

I upgraded the server yesterday, so this seem to be related to recent changes.

**Comment by rawlingsj** [comment]
Not sure why the PR info is missing but it looks like we need some nil checking here https://github.com/jenkins-x/jx/blob/v1.2.88/pkg/jx/cmd/preview.go#L288

**Comment by rawlingsj** [comment]
Lemme add that in
