### ISSUE TITLE
"Invalid Credentials" in Jenkins jobs after success creation of golang-http with GHE

### ISSUE THREAD

**Issue by biancajiang** [jenkins-x/jx#984]
jx create git server for GHE
jx create git token for GHE
jx create cluster aws with GHE
jx create quickstart -l go

All successful.  golang-http, staging, production environment repos all pushed to GHE successfully.

However all three Jenkins jobs' configurations shown "invalid credentials" with the jx created GHE token.  I'm not able to update this token or use a new one in Jenkins either.  Am I missing something here?

Repo scan log from Jenkins:
ERROR: [Thu Jun 07 10:44:10 UTC 2018] Could not update folder level actions from source xxxxxxxxxxxxxxxxxx
hudson.AbortException: Invalid scan credentials bianca-jiang/****** (API Token for acccessing https://github.foo.bar git service inside pipelines) to connect to https://github.foo.bar/api/v3, skipping
	at org.jenkinsci.plugins.github_branch_source.Connector.checkConnectionValidity(Connector.java:435)
	at org.jenkinsci.plugins.github_branch_source.GitHubSCMSource.retrieveActions(GitHubSCMSource.java:1577)
	at jenkins.scm.api.SCMSource.fetchActions(SCMSource.java:746)
	at jenkins.branch.MultiBranchProject.computeChildren(MultiBranchProject.java:588)
	at com.cloudbees.hudson.plugins.folder.computed.ComputedFolder.updateChildren(ComputedFolder.java:276)
	at com.cloudbees.hudson.plugins.folder.computed.FolderComputation.run(FolderComputation.java:165)
	at jenkins.branch.MultiBranchProject$BranchIndexing.run(MultiBranchProject.java:1022)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)

It seems the GHE token works from jx (repos pushed to GHE) but not in the Jenkins jobs? Tried with two aws clusters created by jx, same result.

I tried the same first with public github, this didn't happen and all good. 

jx                 1.2.104
jenkins x platform 0.0.1193
kubernetes cluster v1.9.6
kubectl            v1.10.4
helm client        v2.9.1+g20adb27
helm server        v2.9.1+g20adb27
git                git version 2.15.1 (Apple Git-101)

**Comment by biancajiang** [comment]
So far I think this is not a jenkins-x issue but b/c my ghe and jenkins-x cluster are in different PVCs on aws.

**Comment by xuanzhong** [comment]
@biancajiang  I ran into the same issue. Can you please be more specific on how you resolve this issue? I also use AWS

**Comment by pdutta777** [comment]
I am also facing the same issue
